import { defineConfigScope } from '../../../../../components/Panel/config';
import {
  GAP_OPTIONS,
  WIDTH_OPTIONS,
  WIDTH_WIDE_OPTIONS,
  WIDTH_LG_OPTIONS,
} from '../../../../../components/tailwindSpacingScale';
import {
  DEFAULT_SPLIT_COLUMN_CARD_STACK_CONFIG,
  type SplitColumnCardStackConfig,
} from './stack';

export const SPLIT_COLUMN_CARD_STACK_SCOPE_ID = 'SplitColumnCardPreview/stack' as const;

const whenEnabled = (config: Readonly<SplitColumnCardStackConfig>) => config.enabled;
const whenExplicitNavigationAvailable = (config: Readonly<SplitColumnCardStackConfig>) => (
  config.enabled && config.showArrowControlsEnabled
);
const whenMobileSnapSkippingApplies = (config: Readonly<SplitColumnCardStackConfig>) => (
  config.enabled && !config.mobileCarouselDragFree
);

// Same CtaButtonMotionEasing token set CtaButton/config/panel.ts's own
// easing fields already list — kept local (not exported/shared) since each
// panel.ts in this repo defines its own field options inline.
const MOTION_EASING_OPTIONS = [
  { label: 'LINEAR', value: 'linear' },
  { label: 'STANDARD', value: 'standard' },
  { label: 'EXPRESSIVE', value: 'expressive' },
  { label: 'VISCOUS', value: 'viscous' },
  { label: 'GENTLE', value: 'gentle' },
  { label: 'GAUSSIAN', value: 'gaussian' },
] as const;

export const SPLIT_COLUMN_CARD_STACK_PANEL = defineConfigScope<SplitColumnCardStackConfig>({
  id: SPLIT_COLUMN_CARD_STACK_SCOPE_ID,
  component: 'SplitColumnCardPreview',
  scope: 'stack',
  title: 'Card stack',
  createdAt: '2026-08-08',
  summary: 'Opt-in vertical card stack — layout, next/prev motion, gestures, arrows',
  defaultOpen: false,
  defaultValue: DEFAULT_SPLIT_COLUMN_CARD_STACK_CONFIG,
  fields: [
    {
      kind: 'tabs',
      tabs: [
        {
          id: 'all-sizes',
          label: 'ALL SIZES',
          fields: [
    {
      kind: 'boolean',
      key: 'enabled',
      label: 'Stack mode',
      description: 'Vertical card stack filling the column, paging through the full Articles/Labs list, instead of a single 3:4 card. Off reproduces the original single-card layout unchanged.',
    },
    {
      kind: 'select',
      key: 'cardGap',
      label: 'Card gap',
      options: GAP_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'tabsVisible',
      label: 'Articles/Labs switcher',
      description: 'On: the tab row renders and the stack can switch between Articles and Labs (tab click or horizontal swipe). Off: the whole tab row is omitted, not just the Labs side disabled, and swipe-to-Labs is disabled with it — the stack becomes articles-only rather than hiding the switcher while leaving an undiscoverable way to reach Labs anyway.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'firstArticleTitleAndSummaryOnly',
      label: 'First article: title and summary only',
      description: 'Presents the first Article card — currently “Thinking in systems” — as a non-navigating introduction with only its title and summary. Hides its metadata and read-article CTA, while preserving normal deck selection so it can return to the active position. Later cards and every Lab card retain their full information hierarchy and interactions.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'verticalGesturesEnabled',
      label: 'Vertical scroll/swipe navigation',
      description: 'Trackpad and mouse-wheel movement over the card column steps the stack one card per intentional burst; a one-finger touch or pen swipe directly moves and then commits the stack. At the first and last card, unavailable wheel directions remain native page scroll. Keyboard navigation stays available either way; explicit arrow buttons are governed separately below.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'showArrowControlsEnabled',
      label: 'Show arrow controls',
      description: 'Off (default): completely omits the previous/next arrow controls on every device. The stack remains navigable by scroll/swipe, keyboard arrows, and direct neighbor-card promotion where pointer capability permits. On: devices without a hover-capable pointer render the explicit arrow controls as a fallback.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborRotationDeg',
      label: 'Neighbor tilt',
      description: 'Rest-pose 3D rotation (both X and Y axes) for cards above/below the active one.',
      min: 0,
      max: 60,
      step: 1,
      unit: 'deg',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborScaleDownPercent',
      label: 'Neighbor scale-down',
      min: 0,
      max: 0.8,
      step: 0.01,
      unit: '%',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborOpacity',
      label: 'Neighbor opacity',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborGradientRevealDurationMs',
      label: 'Gradient reveal duration',
      description: 'How long the gradient-mesh cover takes to fade away as a card becomes active, or back in as it becomes a neighbor. Drives both the mesh cover and this slot\'s own rest-opacity fade, so the two move together instead of compounding on two different short windows.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'neighborGradientRevealEasing',
      label: 'Gradient reveal easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborGradientRevealBlurPx',
      label: 'Gradient reveal blur',
      description: 'Backdrop blur applied to the mesh cover only while a card is actually crossing the neighbor/active boundary — never at rest — so the mesh appears to resolve into focus rather than being uncovered by an already-sharp flat wipe. 0 disables the blur.',
      min: 0,
      max: 64,
      step: 2,
      unit: 'px',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborShadowFadeDurationMs',
      label: 'Shadow fade duration',
      description: 'How long the active card\'s own elevation shadow takes to fade in as it becomes active, or fade out as it becomes a neighbor — a real, separately-tweened fade, not driven by elevation alone (the shadow engine\'s own contact layer is strongest at zero elevation, so easing elevation to zero doesn\'t by itself ease the shadow to invisible).',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'neighborShadowFadeEasing',
      label: 'Shadow fade easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborPoseDurationMs',
      label: 'Scale/tilt transition duration',
      description: 'How long a card\'s own rotate+scale transform takes to ease between its active and neighbor rest pose. CSS can only time rotate and scale together (one shared transform property), so this governs both — tune Neighbor tilt above to 0 if only the scale change should be visible.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'neighborPoseEasing',
      label: 'Scale/tilt transition easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'neighborBackgroundMode',
      label: 'Neighbor background',
      description: 'Surface: the same page surface color already painted behind everything else (today\'s only behavior). Transparent: no background of its own — whatever\'s behind shows through. Custom: the fixed color below. Column: the wide split column\'s own color, offset by the amount below.',
      options: [
        { label: 'SURFACE', value: 'surface' },
        { label: 'TRANSPARENT', value: 'transparent' },
        { label: 'CUSTOM', value: 'custom' },
        { label: 'COLUMN', value: 'column' },
      ],
      visibleWhen: whenEnabled,
    },
    {
      kind: 'color',
      key: 'neighborBackgroundCustomColor',
      label: 'Neighbor background custom color',
      visibleWhen: config => config.enabled && config.neighborBackgroundMode === 'custom',
    },
    {
      kind: 'number',
      key: 'neighborBackgroundOffset',
      label: 'Neighbor background offset',
      description: 'How much lighter (positive) or darker (negative) than the split column color the neighbor background is.',
      min: -1,
      max: 1,
      step: 0.01,
      visibleWhen: config => config.enabled && config.neighborBackgroundMode === 'column',
    },
    {
      kind: 'enum',
      key: 'neighborTextColorMode',
      label: 'Neighbor text source',
      description: 'Custom (default): the fixed colors below. Column: both derive from the wide split column\'s own color, contrast-checked and offset by the amounts below.',
      options: [
        { label: 'CUSTOM', value: 'custom' },
        { label: 'COLUMN', value: 'column' },
      ],
      visibleWhen: whenEnabled,
    },
    {
      kind: 'color',
      key: 'neighborTextColor',
      label: 'Neighbor text color',
      description: 'Label, meta, title, excerpt, separator, and CTA — every one of a neighbor card\'s own text elements already renders as this one unified color.',
      visibleWhen: config => config.enabled && config.neighborTextColorMode === 'custom',
    },
    {
      kind: 'color',
      key: 'neighborTopicBorderColor',
      label: 'Neighbor topic border color',
      description: 'Border of the small rounded category/topic tag (e.g. "BIOMIMETICS") on a neighbor card.',
      visibleWhen: config => config.enabled && config.neighborTextColorMode === 'custom',
    },
    {
      kind: 'number',
      key: 'neighborTextOffset',
      label: 'Neighbor text offset',
      description: 'How much lighter (positive) or darker (negative) than the split column color the neighbor text/topic-border search prefers, while Neighbor text source is COLUMN.',
      min: -1,
      max: 1,
      step: 0.01,
      visibleWhen: config => config.enabled && config.neighborTextColorMode === 'column',
    },
    {
      kind: 'number',
      key: 'neighborTextMinContrast',
      label: 'Neighbor text minimum contrast',
      description: 'WCAG contrast ratio neighbor text/topic-border must clear against the wide split column color, while Neighbor text source is COLUMN.',
      min: 1,
      max: 21,
      step: 0.1,
      visibleWhen: config => config.enabled && config.neighborTextColorMode === 'column',
    },
    {
      kind: 'number',
      key: 'neighborBorderColorOffset',
      label: 'Neighbor border color opacity',
      description: 'Opacity (alpha) the neighbor card\'s own resolved text color renders at for its outer border — same exact color, faded, not a lighter/darker tint. 0.38 reads as 62% transparent.',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborBorderHoverOpacity',
      label: 'Neighbor border color opacity (hover)',
      description: 'Opacity (alpha) a settled neighbor card\'s outer border switches to while genuinely hovered, on a hover-capable pointer device only — a separate value from the rest-state opacity above.',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'ctaHoverDurationMs',
      label: 'CTA reveal duration (hover)',
      description: 'How long the active card\'s "Read article" button takes to fade in/out on hover or focus.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'ctaHoverEasing',
      label: 'CTA reveal easing (hover)',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'ctaHoverDelayMs',
      label: 'CTA reveal delay (hover)',
      description: 'How long the pointer must stay in (or out of) the card before the "Read article" button\'s fade in/out even starts — absorbs an incidental cursor pass so the reveal only commits on deliberate hover intent.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'stepStaggerMs',
      label: 'Step cascade delay',
      description: 'Per-slot delay, multiplied by distance from the active slot, so a next/prev step ripples outward instead of moving every card in lockstep.',
      min: 0,
      max: 400,
      step: 10,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'stepTiltDurationMs',
      label: 'Step tilt duration',
      description: 'Each card\'s rotate + scale + opacity sub-phase — runs first, before the translate sub-phase begins.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'stepTiltEasing',
      label: 'Step tilt easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'stepTranslateDurationMs',
      label: 'Step translate duration',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'stepTranslateEasing',
      label: 'Step translate easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'stepCommitThresholdPx',
      label: 'Step commit threshold',
      description: 'How far a vertical wheel/touch/pen gesture must travel before it commits to a step, instead of settling back to the resting position.',
      min: 8,
      max: 200,
      step: 2,
      unit: 'px',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'stepVelocityScalingEnabled',
      label: 'Velocity-scaled step duration',
      description: 'On: a fast wheel/pointer release plays the committed step faster (toward Step settle minimum scale below), the way a hard flick lands sooner in Embla-style attraction physics. Off: every committed step always animates at the full Step translate duration above, regardless of gesture speed. Keyboard-triggered steps always use the full duration either way.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'stepSettleMinDurationScale',
      label: 'Step settle minimum scale',
      description: 'Fraction of Step translate duration used once a release reaches Step settle max flick speed below. 1 disables scaling in effect.',
      min: 0.2,
      max: 1,
      step: 0.05,
      unit: '%',
      visibleWhen: config => config.enabled && config.stepVelocityScalingEnabled,
    },
    {
      kind: 'number',
      key: 'stepVelocityMaxFlickPxPerMs',
      label: 'Step settle max flick speed',
      description: 'Release speed at which the minimum duration scale above is fully reached. Slower releases interpolate linearly between the full duration and the minimum scale.',
      min: 0.1,
      max: 5,
      step: 0.1,
      unit: 'px/ms',
      visibleWhen: config => config.enabled && config.stepVelocityScalingEnabled,
    },
    {
      kind: 'boolean',
      key: 'verticalEdgeSpringEnabled',
      label: 'Vertical edge spring release',
      description: 'On: overscrolling past the first/last card releases into a physically-integrated damped spring instead of a flat CSS snap back to the resting position — the same model the horizontal Articles/Labs edge already uses internally. Off: today\'s plain CSS settle.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'verticalEdgeSpringStiffness',
      label: 'Vertical edge spring stiffness',
      min: 40,
      max: 800,
      step: 10,
      integer: true,
      visibleWhen: config => config.enabled && config.verticalEdgeSpringEnabled,
    },
    {
      kind: 'number',
      key: 'verticalEdgeSpringDamping',
      label: 'Vertical edge spring damping',
      min: 2,
      max: 120,
      step: 1,
      integer: true,
      visibleWhen: config => config.enabled && config.verticalEdgeSpringEnabled,
    },
    {
      kind: 'number',
      key: 'verticalEdgeSpringMaxDurationMs',
      label: 'Vertical edge spring max duration',
      description: 'Safety ceiling — a spring that reaches a small displacement and velocity ends sooner. 0 disables the spring outright regardless of the toggle above.',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: config => config.enabled && config.verticalEdgeSpringEnabled,
    },
    {
      kind: 'number',
      key: 'swipePushDistancePercent',
      label: 'Swipe push distance',
      description: 'Horizontal Articles/Labs swipe — how far the outgoing/incoming card set travels, as a fraction of the container width.',
      min: 0,
      max: 1,
      step: 0.05,
      unit: '%',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'swipeDurationMs',
      label: 'Swipe duration',
      min: 0,
      max: 1200,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'enum',
      key: 'swipeEasing',
      label: 'Swipe easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'arrowSizePx',
      label: 'Arrow size',
      min: 10,
      max: 48,
      step: 1,
      unit: 'px',
      integer: true,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'color',
      key: 'arrowIdleColor',
      label: 'Arrow idle color',
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'color',
      key: 'arrowHoverColor',
      label: 'Arrow hover color',
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'number',
      key: 'arrowIdleOpacity',
      label: 'Arrow idle opacity',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'number',
      key: 'arrowHoverOpacity',
      label: 'Arrow hover opacity',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'number',
      key: 'arrowDisabledOpacity',
      label: 'Arrow disabled opacity',
      min: 0,
      max: 1,
      step: 0.01,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'number',
      key: 'arrowHoverTransitionMs',
      label: 'Arrow hover-in duration',
      min: 0,
      max: 1000,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'enum',
      key: 'arrowHoverEasing',
      label: 'Arrow hover-in easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'number',
      key: 'arrowMouseOutTransitionMs',
      label: 'Arrow hover-out duration',
      min: 0,
      max: 1000,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'enum',
      key: 'arrowMouseOutEasing',
      label: 'Arrow hover-out easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: whenExplicitNavigationAvailable,
    },
    {
      kind: 'boolean',
      key: 'cursorIntentEnabled',
      label: 'Dwell auto-promote',
      description: 'On hover-capable pointer devices (mouse/trackpad), hovering a neighbor card long enough auto-promotes it to active with no click. Off: that ambient layer is gone, but a plain click on a neighbor still always promotes it. Arrow rendering is governed independently by Show arrow controls above. Touch/coarse-pointer devices are unaffected by this dwell behavior. Independent of the proximity opacity/scale toggles below.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'dwellThresholdMs',
      label: 'Dwell auto-promote threshold',
      description: 'How long the cursor must stay over a neighbor before it\'s automatically promoted to active. Leaving before this resets progress to nothing. Suppressed under prefers-reduced-motion; click-to-promote still works instantly.',
      min: 150,
      max: 3000,
      step: 50,
      unit: 'ms',
      integer: true,
      visibleWhen: config => config.enabled && config.cursorIntentEnabled,
    },
    {
      kind: 'boolean',
      key: 'neighborProximityOpacityEnabled',
      label: 'Proximity opacity',
      description: 'A neighbor card brightens from its rest opacity toward full opacity as the cursor nears/enters it. Independent of Cursor-intent navigation above — works standalone as ambient decoration.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'boolean',
      key: 'neighborProximityScaleEnabled',
      label: 'Proximity scale',
      description: 'A neighbor card also grows slightly as the cursor nears/enters it, reusing the same proximity signal as opacity above. Independent of it — either, both, or neither can be on.',
      visibleWhen: whenEnabled,
    },
    {
      kind: 'number',
      key: 'neighborProximityScaleAmount',
      label: 'Proximity scale amount',
      description: 'How much larger a neighbor grows, as a fraction added to its rest scale, once the cursor is fully inside its box.',
      min: 0,
      max: 0.5,
      step: 0.01,
      unit: '%',
      visibleWhen: config => config.enabled && config.neighborProximityScaleEnabled,
    },
    {
      kind: 'number',
      key: 'neighborProximityRadiusPx',
      label: 'Proximity radius',
      description: 'Distance from a neighbor card at which proximity starts ramping toward full — shared by whichever of opacity/scale above is on.',
      min: 40,
      max: 640,
      step: 10,
      unit: 'px',
      integer: true,
      visibleWhen: config => config.enabled
        && (config.neighborProximityOpacityEnabled || config.neighborProximityScaleEnabled),
    },
    {
      kind: 'enum',
      key: 'neighborProximityEasing',
      label: 'Proximity distance easing',
      options: [
        { label: 'LINEAR', value: 'linear' },
        { label: 'SMOOTHSTEP', value: 'smoothstep' },
        { label: 'SMOOTHERSTEP', value: 'smootherstep' },
        { label: 'EASE OUT CUBIC', value: 'ease-out-cubic' },
      ],
      visibleWhen: config => config.enabled
        && (config.neighborProximityOpacityEnabled || config.neighborProximityScaleEnabled),
    },
    {
      kind: 'number',
      key: 'neighborProximityAttackMs',
      label: 'Proximity ramp-in time',
      min: 16,
      max: 600,
      step: 10,
      unit: 'ms',
      integer: true,
      visibleWhen: config => config.enabled
        && (config.neighborProximityOpacityEnabled || config.neighborProximityScaleEnabled),
    },
    {
      kind: 'number',
      key: 'neighborProximityReleaseMs',
      label: 'Proximity ramp-out time',
      min: 16,
      max: 1000,
      step: 10,
      unit: 'ms',
      integer: true,
      visibleWhen: config => config.enabled
        && (config.neighborProximityOpacityEnabled || config.neighborProximityScaleEnabled),
    },
    {
      kind: 'number',
      key: 'neighborSettleOpacityTransitionMs',
      label: 'Settle opacity transition',
      description: 'Duration of a neighbor\'s very first opacity ramp right as it settles into place — softens the case where the cursor is already resting on the card the moment a step finishes, instead of the proximity engine\'s normal fast-attack ramp-in kicking in on an already-large target. Every ramp after this one still uses Proximity ramp-in/-out time above.',
      min: 0,
      max: 1000,
      step: 20,
      unit: 'ms',
      integer: true,
      visibleWhen: config => config.enabled && config.neighborProximityOpacityEnabled,
    },
    {
      kind: 'enum',
      key: 'neighborSettleOpacityEasing',
      label: 'Settle opacity easing',
      options: MOTION_EASING_OPTIONS,
      visibleWhen: config => config.enabled && config.neighborProximityOpacityEnabled,
    },
          ],
        },
        {
          id: 'mobile',
          label: 'MOBILE (< 768px)',
          fields: [
            {
              kind: 'select',
              key: 'cardWidth',
              label: 'Card width',
              description: 'Mobile card-deck width. Full (100%) fills the parent content viewport and adapts with it.',
              options: WIDTH_OPTIONS,
              visibleWhen: whenEnabled,
            },
            {
              kind: 'boolean',
              key: 'legacyCardWidthEnabled',
              label: 'Enforce legacy card width (w-96)',
              description: 'Mobile only. On forces the original fixed w-96 width. Off uses Card width above, whose default Full (100%) fills the parent content viewport.',
              visibleWhen: whenEnabled,
            },
            {
              kind: 'number',
              key: 'mobileCarouselDuration',
              label: 'Carousel settle duration',
              description: 'Embla attraction strength for API-driven settling. This is a dimensionless physics value, not milliseconds; higher values settle more slowly. Touch only below 768px.',
              min: 20,
              max: 60,
              step: 1,
              integer: true,
              visibleWhen: whenEnabled,
            },
            {
              kind: 'boolean',
              key: 'mobileCarouselDragFree',
              label: 'Drag free momentum',
              description: 'Allows a touch drag to settle between cards with momentum. Off keeps one complete card snapped into place.',
              visibleWhen: whenEnabled,
            },
            {
              kind: 'boolean',
              key: 'mobileCarouselSkipSnaps',
              label: 'Allow snap skipping',
              description: 'Allows a decisive flick to pass more than one card. Embla ignores this option while Drag free momentum is on.',
              visibleWhen: whenMobileSnapSkippingApplies,
            },
            {
              kind: 'boolean',
              key: 'mobileCarouselLoop',
              label: 'Loop cards',
              description: 'Wraps navigation between the first and last card. Off keeps physical, resisted collection edges.',
              visibleWhen: whenEnabled,
            },
            {
              kind: 'select',
              key: 'mobileCarouselGap',
              label: 'Card separation',
              description: 'Touch-carousel edge-to-edge separation between cards inside the full-width mobile viewport. Uses the shared Tailwind spacing scale.',
              options: GAP_OPTIONS,
              visibleWhen: whenEnabled,
            },
          ],
        },
        {
          id: 'tablet',
          label: 'TABLET (≥ 768px)',
          fields: [
            {
              kind: 'select',
              key: 'cardWidthWide',
              label: 'Card width (≥ tablet)',
              description: 'Tablet card-deck width. Full (100%) fills the parent content viewport and adapts with it.',
              options: WIDTH_WIDE_OPTIONS,
              visibleWhen: whenEnabled,
            },
            {
              kind: 'boolean',
              key: 'legacyCardWidthEnabledWide',
              label: 'Enforce legacy card width (w-96)',
              description: 'Tablet only. On forces md:w-96. Off uses Card width above, whose default md:w-full fills the parent content viewport.',
              visibleWhen: whenEnabled,
            },
          ],
        },
        {
          id: 'desktop',
          label: 'DESKTOP (≥ 1024px)',
          fields: [
            {
              kind: 'select',
              key: 'cardWidthLg',
              label: 'Card width (≥ desktop)',
              description: 'Desktop card-deck width. Full (100%) fills the parent content viewport and adapts with it.',
              options: WIDTH_LG_OPTIONS,
              visibleWhen: whenEnabled,
            },
            {
              kind: 'boolean',
              key: 'legacyCardWidthEnabledLg',
              label: 'Enforce legacy card width (w-96)',
              description: 'Desktop only. On forces lg:w-96. Off uses Card width above, whose default lg:w-full fills the parent content viewport.',
              visibleWhen: whenEnabled,
            },
          ],
        },
      ],
    },
  ],
  copy: {
    targetFile: 'experiences/abstract/components/SplitColumnCardPreview/config/stack.ts',
    targetSymbol: 'DEFAULT_SPLIT_COLUMN_CARD_STACK_CONFIG',
    targetType: 'SplitColumnCardStackConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});
