import type { ConfigScopeEntry } from '../../../../../components/Panel/config';
import { defineConfigScope } from '../../../../../components/Panel/config';
import { DEFAULT_WORDMARK_CONFIG, type WordmarkConfig } from './wordmark';

export const WORDMARK_SCOPE_ID = 'Wordmark/logo' as const;

const WORDMARK_INTRO_EASING_OPTIONS = [
  { label: 'EASE IN OUT', value: 'ease-in-out' },
  { label: 'EASE', value: 'ease' },
  { label: 'EASE IN', value: 'ease-in' },
  { label: 'EASE OUT', value: 'ease-out' },
  { label: 'LINEAR', value: 'linear' },
  { label: 'STANDARD', value: 'cubic-bezier(0.2, 0, 0, 1)' },
  { label: 'EXPRESSIVE', value: 'cubic-bezier(0.22, 1, 0.36, 1)' },
  { label: 'VISCOUS', value: 'cubic-bezier(0.16, 1, 0.3, 1)' },
  { label: 'GENTLE', value: 'cubic-bezier(0.33, 1, 0.68, 1)' },
] as const;

const WORDMARK_SCALE_PIVOT_OPTIONS = [
  { label: 'CENTER', value: 'center' },
  { label: 'TOP LEFT', value: 'top-left' },
  { label: 'TOP CENTER', value: 'top-center' },
  { label: 'TOP RIGHT', value: 'top-right' },
  { label: 'LEFT CENTER', value: 'left-center' },
  { label: 'RIGHT CENTER', value: 'right-center' },
  { label: 'BOTTOM LEFT', value: 'bottom-left' },
  { label: 'BOTTOM CENTER', value: 'bottom-center' },
  { label: 'BOTTOM RIGHT', value: 'bottom-right' },
] as const;

const WORDMARK_FIELDS: ReadonlyArray<ConfigScopeEntry<WordmarkConfig>> = [
  {
    kind: 'group',
    label: 'Color',
    fields: [
      {
        kind: 'enum',
        key: 'colorMode',
        label: 'Color mode',
        description: 'Adaptive uses the page\'s own supplied fallback gradient (e.g. a live-sampled hero). Custom applies the flat color below. Surface derives from the page surface color. Column (default) derives from the split column\'s own color underneath the logo, contrast-checked.',
        options: [
          { label: 'ADAPTIVE', value: 'adaptive' },
          { label: 'CUSTOM', value: 'custom' },
          { label: 'SURFACE', value: 'surface' },
          { label: 'COLUMN', value: 'column' },
        ],
      },
      {
        kind: 'color',
        key: 'color',
        label: 'Custom color',
        visibleWhen: config => config.colorMode === 'custom',
      },
      {
        kind: 'number',
        key: 'surfaceOffset',
        label: 'Offset',
        description: 'How much lighter (positive) or darker (negative) than the base/contrast-search result the resolved color is.',
        min: -1,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.colorMode === 'surface' || config.colorMode === 'column',
      },
      {
        kind: 'number',
        key: 'columnTextMinContrast',
        label: 'Minimum contrast ratio',
        description: 'Target WCAG contrast ratio against the split column\'s own physical color. If physically impossible for that background, the highest-contrast black/white endpoint is used.',
        min: 1,
        max: 21,
        step: 0.1,
        visibleWhen: config => config.colorMode === 'column',
      },
      {
        kind: 'number',
        key: 'colorTransitionMs',
        label: 'Color change transition',
        description: 'How long the gradient cross-fades when its stops change at runtime (e.g. a live palette edit).',
        min: 0,
        max: 2000,
        step: 20,
        unit: 'ms',
        integer: true,
      },
    ],
  },
  {
    kind: 'group',
    label: 'Layout',
    fields: [
      {
        kind: 'number',
        key: 'maxWidthPx',
        label: 'Max width',
        description: 'Hard cap on the wordmark\'s rendered width, on top of the responsive logoWidth/desktopLogoWidth sizing — applies to every page since SiteHeader is the sole global mount point.',
        min: 100,
        max: 960,
        step: 10,
        unit: 'px',
        integer: true,
      },
    ],
  },
  {
    kind: 'group',
    label: 'Intro animation',
    fields: [
      {
        kind: 'boolean',
        key: 'introEnabled',
        label: 'Animate on mount',
        description: 'Off: every glyph renders in its resting state immediately, no stagger.',
      },
      {
        kind: 'number',
        key: 'introInitialDelayS',
        label: 'Initial delay',
        description: 'Delay before the first glyph\'s own fade/scale starts.',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 's',
        visibleWhen: config => config.introEnabled,
      },
      {
        kind: 'number',
        key: 'introStepDelayS',
        label: 'Stagger step delay',
        description: 'Extra delay added per glyph, so letters fade in one after another rather than together.',
        min: 0,
        max: 1,
        step: 0.01,
        unit: 's',
        visibleWhen: config => config.introEnabled,
      },
      {
        kind: 'number',
        key: 'introDurationS',
        label: 'Duration',
        description: 'Duration of each glyph\'s own fade/scale animation.',
        min: 0,
        max: 4,
        step: 0.05,
        unit: 's',
        visibleWhen: config => config.introEnabled,
      },
      {
        kind: 'enum',
        key: 'introEasing',
        label: 'Easing',
        options: WORDMARK_INTRO_EASING_OPTIONS,
        visibleWhen: config => config.introEnabled,
      },
      {
        kind: 'enum',
        key: 'introDirection',
        label: 'Direction',
        description: 'Forward: first glyph fades first. Reverse (default): last glyph fades first.',
        options: [
          { label: 'FORWARD', value: 'forward' },
          { label: 'REVERSE', value: 'reverse' },
        ],
        visibleWhen: config => config.introEnabled,
      },
      {
        kind: 'select',
        key: 'introScalePivot',
        label: 'Scale pivot',
        description: 'Transform-origin each glyph scales from.',
        options: WORDMARK_SCALE_PIVOT_OPTIONS,
        visibleWhen: config => config.introEnabled,
      },
    ],
  },
  {
    kind: 'group',
    label: 'Intro bloom',
    visibleWhen: config => config.introEnabled,
    fields: [
      {
        kind: 'boolean',
        key: 'introBloomEnabled',
        label: 'Enable bloom',
        description: 'Off: brightness stays flat at the resting value below (no bloom pulse) — fade/scale still run.',
      },
      {
        kind: 'number',
        key: 'introBloomBase',
        label: 'Resting brightness',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 'x',
        visibleWhen: config => config.introBloomEnabled,
      },
      {
        kind: 'number',
        key: 'introBloomPeak',
        label: 'Peak brightness',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 'x',
        visibleWhen: config => config.introBloomEnabled,
      },
      {
        kind: 'number',
        key: 'introBloomInitialDelayS',
        label: 'Bloom initial delay',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 's',
        visibleWhen: config => config.introBloomEnabled,
      },
      {
        kind: 'number',
        key: 'introBloomStepDelayS',
        label: 'Bloom stagger step delay',
        min: 0,
        max: 1,
        step: 0.01,
        unit: 's',
        visibleWhen: config => config.introBloomEnabled,
      },
    ],
  },
];

export const WORDMARK_PANEL = defineConfigScope<WordmarkConfig>({
  id: WORDMARK_SCOPE_ID,
  component: 'Wordmark',
  scope: 'logo',
  title: 'Wordmark',
  createdAt: '2026-08-28',
  summary: 'Logo color, adaptive column derivation, and intro animation — shared across every page',
  defaultOpen: false,
  defaultValue: DEFAULT_WORDMARK_CONFIG,
  fields: WORDMARK_FIELDS,
  copy: {
    targetFile: 'experiences/abstract/components/SiteHeader/config/wordmark.ts',
    targetSymbol: 'DEFAULT_WORDMARK_CONFIG',
    targetType: 'WordmarkConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});
