[build]
  command = "npm run build:static"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "out"
  autoLaunch = false
  framework = "#custom"
