import { defineConfigScope } from '../../../../../components/Panel/config';
import {
  DEFAULT_ABSTRACT_HERO_CTA_COMPOSER_CONFIG,
  type AbstractHeroCtaComposerConfig,
} from './registered';

export const ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_SCOPE_ID =
  'AbstractHeroCtaComposer/entrance' as const;

const MOTION_EASING_OPTIONS = [
  { label: 'LINEAR', value: 'linear' },
  { label: 'STANDARD', value: 'standard' },
  { label: 'EXPRESSIVE', value: 'expressive' },
  { label: 'VISCOUS', value: 'viscous' },
  { label: 'GENTLE', value: 'gentle' },
  { label: 'GAUSSIAN', value: 'gaussian' },
] as const;

const REVEAL_DISTRIBUTION_OPTIONS = [
  { label: 'LINEAR', value: 'linear' },
  { label: 'GAUSSIAN', value: 'gaussian' },
  { label: 'GAUSSIAN INVERSE', value: 'gaussian-inverse' },
] as const;

export const ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_PANEL =
  defineConfigScope<AbstractHeroCtaComposerConfig>({
    id: ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_SCOPE_ID,
    component: 'AbstractHeroCtaComposer',
    scope: 'entrance',
    title: 'Hero CTA composer',
    createdAt: '2026-07-24',
    summary: 'Two-line intro timing · fade-out · elevation rise · placeholder reveal',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_HERO_CTA_COMPOSER_CONFIG,
    fields: [
      {
        kind: 'group',
        label: 'Entrance timing',
        fields: [
          {
            kind: 'number',
            key: 'introLine1HoldMs',
            label: 'First line hold',
            description: 'How long the composer holds on its fully-revealed first line ("Tell me what you\'re working on") before it fades out, below.',
            min: 0,
            max: 8000,
            step: 50,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'number',
            key: 'introLine1ExitDurationMs',
            label: 'First line fade-out duration',
            description: 'How long the fully-revealed first line takes to fade out as one plain block — a single opacity transition, not a per-character animation — once the hold above ends, before the real placeholder enters.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'enum',
            key: 'introLine1ExitEasing',
            label: 'First line fade-out easing',
            options: MOTION_EASING_OPTIONS,
          },
          {
            kind: 'number',
            key: 'elevationRiseDurationMs',
            label: 'Elevation rise duration',
            description: 'How long the resting shadow elevation takes to tween from flat (0) up to Composer elevation, below, once the first line has finished fading out.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'enum',
            key: 'elevationRiseEasing',
            label: 'Elevation rise easing',
            options: MOTION_EASING_OPTIONS,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Composer appearance',
        fields: [
          {
            kind: 'number',
            key: 'composerElevationPx',
            label: 'Composer elevation',
            description: 'Pinned resting elevation once morphed — independent of the CTA\'s own shared shadow elevation. Defaults to the same value as contact.tsx\'s own composer for visual parity.',
            min: 0,
            max: 32,
            step: 0.5,
            unit: 'px',
          },
          {
            kind: 'number',
            key: 'placeholderMinContrast',
            label: 'Placeholder min contrast',
            description: 'Minimum contrast ratio the revealed placeholder text must clear against the page surface color.',
            min: 1,
            max: 7,
            step: 0.1,
          },
          {
            kind: 'enum',
            key: 'composerAlign',
            label: 'Alignment',
            description: 'The pill\'s own horizontal placement — Left keeps it flush with the left-aligned headline/paragraph copy above it; Center matches contact.tsx\'s own composer instead.',
            options: [
              { label: 'LEFT', value: 'left' },
              { label: 'CENTER', value: 'center' },
            ],
          },
          {
            kind: 'enum',
            key: 'chrome',
            label: 'Chrome',
            description: 'DEFAULT is today\'s shadowed, border-2 pill (shared look with contact.tsx\'s own composer). TAG PILL rebuilds this hero-only instance from the site\'s own card-tag idiom instead — a hairline border, no shadow, monospace/letterspaced placeholder and submit glyph. Opt-in: contact.tsx never reads this field.',
            options: [
              { label: 'DEFAULT', value: 'default' },
              { label: 'TAG PILL', value: 'tagPill' },
            ],
          },
        ],
      },
      {
        kind: 'group',
        label: 'Placeholder reveal',
        fields: [
          {
            kind: 'number',
            key: 'heroContainerFadeInDurationMs',
            label: 'Container fade-in duration',
            description: 'Defaults to 0 — this composer is the first thing in its spot in the hero, so appearing instantly reads fine. Raise it for a deliberate cross-fade on mount.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'enum',
            key: 'heroContainerFadeInEasing',
            label: 'Container fade-in easing',
            options: MOTION_EASING_OPTIONS,
          },
          {
            kind: 'number',
            key: 'heroPlaceholderRevealInitialDelayMs',
            label: 'First line reveal gap',
            description: 'Gap after the container fade before the first intro line starts its own per-character reveal. The second line (the real placeholder) reuses the step delay/duration/easing below but starts immediately once the first line\'s hold ends.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'number',
            key: 'heroPlaceholderRevealStepDelayMs',
            label: 'Base ms per character',
            description: 'The base linear pacing rate each line\'s own stagger step is inferred from (this * that line\'s own time dilation, below). Always a perfectly even step between characters — never run through an easing curve, which is what keeps the stagger evenly distributed.',
            min: 0,
            max: 200,
            step: 1,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'number',
            key: 'heroPlaceholderRevealUnitDurationMs',
            label: 'Character fade duration',
            description: 'Each character\'s own fade-in duration, shared across both lines.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'enum',
            key: 'heroPlaceholderRevealEasing',
            label: 'Character fade easing',
            description: 'One shared curve applied to each character\'s own local opacity/transform progress — the same way AbstractPostDock\'s own card intro applies one shared easing to each card\'s local progress. Never applied to cross-character delay.',
            options: MOTION_EASING_OPTIONS,
          },
          {
            kind: 'enum',
            key: 'introRevealDistribution',
            label: 'Reveal distribution',
            description: 'Shapes each character\'s own duration (not delay) via a Gaussian bell curve over character index — mirrors AbstractPostDock\'s own card-intro distribution exactly. Linear (default): every character gets the same duration.',
            options: REVEAL_DISTRIBUTION_OPTIONS,
          },
          {
            kind: 'number',
            key: 'introRevealCadenceAmount',
            label: 'Reveal cadence amount',
            description: '0..1 strength of the Gaussian duration variation above — 0 (default) means every character\'s duration is the same regardless of distribution.',
            min: 0,
            max: 1,
            step: 0.05,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Per-line pacing',
        fields: [
          {
            kind: 'number',
            key: 'introLine1TimeDilation',
            label: 'Line 1 time dilation',
            description: 'Multiplier on top of the inferred base stagger step for the first line ("Tell me what you\'re working on"). 1 = exactly the inferred pacing.',
            min: 0.25,
            max: 4,
            step: 0.05,
          },
          {
            kind: 'number',
            key: 'introLine2TimeDilation',
            label: 'Line 2 time dilation',
            description: 'Multiplier on top of the inferred base stagger step for the second line (the real placeholder).',
            min: 0.25,
            max: 4,
            step: 0.05,
          },
          {
            kind: 'number',
            key: 'introUnitTranslateYPx',
            label: 'Character drift',
            description: 'Vertical distance (px) each character settles down from as it enters. 0 disables this channel — a plain opacity fade. Doesn\'t apply to line 1\'s fade-out, which is a plain whole-block opacity transition with no per-character motion.',
            min: 0,
            max: 40,
            step: 1,
            unit: 'px',
            integer: true,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Placeholder color',
        fields: [
          {
            kind: 'number',
            key: 'placeholderColorTransitionDurationMs',
            label: 'Color transition duration',
            description: 'How long the placeholder text color takes to ease from the first line\'s color to the real placeholder\'s own (more muted) color — starting once both lines have fully finished revealing.',
            min: 0,
            max: 2000,
            step: 10,
            unit: 'ms',
            integer: true,
          },
          {
            kind: 'enum',
            key: 'placeholderColorTransitionEasing',
            label: 'Color transition easing',
            options: MOTION_EASING_OPTIONS,
          },
        ],
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractHeroCtaComposer/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_HERO_CTA_COMPOSER_CONFIG',
      targetType: 'AbstractHeroCtaComposerConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });
