import { defineConfigScope } from '../../../../components/Panel/config';
import {
  PADDING_TOP_OPTIONS,
  PADDING_RIGHT_OPTIONS,
  PADDING_BOTTOM_OPTIONS,
  PADDING_LEFT_OPTIONS,
} from '../../../../components/tailwindSpacingScale';
import {
  DEFAULT_MOBILE_PINNED_ARTICLE_SECTION_CONFIG,
  MOBILE_PINNED_ARTICLE_SECTION_SCOPE_ID,
  type MobilePinnedArticleSectionConfig,
} from './MobilePinnedArticleSection.config';

export { MOBILE_PINNED_ARTICLE_SECTION_SCOPE_ID };

// `kind: 'select'`, not 'enum' — these familiar easing names recur several
// times in the same panel, so native selects remain much easier to scan than
// repeated segmented-control rows.
const MOTION_EASING_OPTIONS = [
  { label: 'Linear', value: 'linear' },
  { label: 'Ease', value: 'ease' },
  { label: 'Ease in', value: 'easeIn' },
  { label: 'Ease out', value: 'easeOut' },
  { label: 'Ease in out', value: 'easeInOut' },
] as const;

export const MOBILE_PINNED_ARTICLE_SECTION_PANEL =
  defineConfigScope<MobilePinnedArticleSectionConfig>({
    id: MOBILE_PINNED_ARTICLE_SECTION_SCOPE_ID,
    component: 'MobilePinnedArticleSection',
    scope: 'layout',
    title: 'Mobile pinned articles',
    createdAt: '2026-09-03',
    summary: 'Mobile carousel and article-list viewport proportions',
    defaultOpen: false,
    defaultValue: DEFAULT_MOBILE_PINNED_ARTICLE_SECTION_CONFIG,
    hiddenKeys: ['listHeightPercent'],
    fields: [
      { kind: 'number', key: 'visibleRowsLargePhone', label: 'Rows on large phones', min: 1, max: 6, step: 1, integer: true },
      { kind: 'number', key: 'visibleRowsSmallPhone', label: 'Rows on small phones', min: 1, max: 6, step: 1, integer: true },
      { kind: 'number', key: 'smallPhoneMaxHeightPx', label: 'Small phone height', min: 480, max: 900, step: 10, unit: 'px', integer: true },
      { kind: 'number', key: 'expandedPanelHeightPercent', label: 'Expanded panel height', min: 50, max: 95, step: 1, unit: '%' },
      { kind: 'number', key: 'carouselHeightPercent', label: 'Carousel height', min: 40, max: 80, step: 1, unit: '%' },
      { kind: 'number', key: 'panelOpacity', label: 'Panel opacity', min: 0, max: 1, step: 0.01 },
      { kind: 'number', key: 'peekHeightSvh', label: 'Initial peek height', min: 4, max: 24, step: 1, unit: 'svh' },
      { kind: 'number', key: 'scrollEffortMultiplier', label: 'Scroll effort multiplier', min: 0.5, max: 2, step: 0.05 },
      {
        kind: 'boolean',
        key: 'scrollDrivenNavigationEnabled',
        label: 'Scroll-driven carousel nav',
        description: 'Off (default): only the list and carousel swipe change the active article. On: page scroll also drives it (legacy behavior).',
      },
      {
        kind: 'enum',
        key: 'fullListPresentation',
        label: 'Full-list presentation',
        description: 'Glass panel keeps the existing bottom-sheet view. Card flip rotates the active card 190° to reveal the complete article list and an in-card Close control on its reverse face.',
        options: [
          { label: 'Glass panel', value: 'glassPanel' },
          { label: 'Card flip', value: 'cardFlip' },
        ],
      },
      {
        // 'select', not 'enum' — AGENTS.md's own hard ceiling: past ~6-8
        // options, a SegmentedControl row (kind: 'enum') renders as an
        // unreadable wall of overlapping/truncated labels. The shared
        // PADDING_TOP/RIGHT/BOTTOM/LEFT_OPTIONS catalogs below have 34
        // entries each (tailwindSpacingScale.ts). Segregated per-edge
        // (operator ask) instead of one shared X/Y pair.
        kind: 'select',
        key: 'expandedListPaddingTop',
        label: 'Expanded list top padding',
        options: PADDING_TOP_OPTIONS,
      },
      {
        kind: 'select',
        key: 'expandedListPaddingRight',
        label: 'Expanded list right padding',
        options: PADDING_RIGHT_OPTIONS,
      },
      {
        kind: 'select',
        key: 'expandedListPaddingBottom',
        label: 'Expanded list bottom padding',
        options: PADDING_BOTTOM_OPTIONS,
      },
      {
        kind: 'select',
        key: 'expandedListPaddingLeft',
        label: 'Expanded list left padding',
        options: PADDING_LEFT_OPTIONS,
      },
      {
        kind: 'color',
        key: 'expandedListBackgroundColor',
        label: 'Expanded list background',
        description: 'Leave empty to inherit the panel’s own background color.',
      },
      { kind: 'number', key: 'expandedListBackgroundOpacity', label: 'Expanded list background opacity', min: 0, max: 1, step: 0.01 },
      {
        kind: 'number',
        key: 'expandedListBackdropBlurPx',
        label: 'Expanded list backdrop blur',
        min: 0,
        max: 40,
        step: 1,
        unit: 'px',
      },
      {
        kind: 'number',
        key: 'expandedCarouselBehindOpacity',
        label: 'Card opacity behind expanded list',
        description: 'Opacity of the collapsed carousel card still visible above the list while it\'s expanded.',
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        kind: 'boolean',
        key: 'expandedForcesMaxBackgroundDarken',
        label: 'Expanding forces max background darken',
        description: 'While the list is expanded, force the page\'s own scroll-gradient background to its maximum darken level, independent of the real scroll position — so the backdrop reads as settled while reading instead of chasing scroll position during a scroll-locked, modal-like view.',
      },
      {
        kind: 'number',
        key: 'panelExpandDurationMs',
        label: 'Expand: panel open',
        description: 'How long the panel takes to grow open when its full list is expanded.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'select',
        key: 'panelExpandEasing',
        label: 'Expand: panel open easing',
        options: MOTION_EASING_OPTIONS,
      },
      {
        kind: 'number',
        key: 'panelExpandFirstRowOverlapPercent',
        label: 'Expand: panel / first-row overlap',
        description: 'How much of the panel-opening duration overlaps the first row entrance. 0% keeps the panel and rows sequential; 100% starts them together.',
        min: 0,
        max: 100,
        step: 1,
        unit: '%',
        integer: true,
      },
      {
        kind: 'number',
        key: 'rowFadeInDelayMs',
        label: 'Expand: extra first-row delay',
        description: 'Extra delay before the first row begins. At 0% panel overlap it follows the panel opening; otherwise it is added to the overlap timing.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'number',
        key: 'rowFadeInDurationMs',
        label: 'Expand: row fade-in',
        description: 'How long each row takes to fade its opacity in. The row-to-row overlap control determines when the next row starts.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'select',
        key: 'rowFadeInEasing',
        label: 'Expand: row fade-in easing',
        options: MOTION_EASING_OPTIONS,
      },
      {
        kind: 'number',
        key: 'rowFadeInOverlapPercent',
        label: 'Expand: row-to-row overlap',
        description: 'How much of one row entrance overlaps the next. 0% is sequential; 100% starts every row together.',
        min: 0,
        max: 100,
        step: 1,
        unit: '%',
        integer: true,
      },
      {
        kind: 'number',
        key: 'rowFadeOutDurationMs',
        label: 'Select: row fade-out',
        description: 'On tapping a row in the expanded list, how long each row takes to fade its opacity out. Row and panel overlap controls determine the rest of the exit timing.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'select',
        key: 'rowFadeOutEasing',
        label: 'Select: row fade-out easing',
        options: MOTION_EASING_OPTIONS,
      },
      {
        kind: 'number',
        key: 'rowFadeOutOverlapPercent',
        label: 'Select: row-to-row overlap',
        description: 'How much of one row exit overlaps the next. 0% is sequential; 100% starts every row together.',
        min: 0,
        max: 100,
        step: 1,
        unit: '%',
        integer: true,
      },
      {
        kind: 'number',
        key: 'panelCollapseFirstRowOverlapPercent',
        label: 'Select: panel / first-row overlap',
        description: 'How much of the row-exit cascade overlaps panel close. 0% waits for the final row; 100% starts panel close with the first row. Closing completes only after both motions finish.',
        min: 0,
        max: 100,
        step: 1,
        unit: '%',
        integer: true,
      },
      {
        kind: 'number',
        key: 'panelCollapseDelayMs',
        label: 'Select: extra panel-close delay',
        description: 'Extra delay added after the selected panel/row overlap point. At 0% overlap, it is the pause after the final row exits.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'number',
        key: 'panelCollapseDurationMs',
        label: 'Select: panel close',
        description: 'How long the persistent glass panel takes to return to its compact height, or the flipped card takes to return to its front face. The carousel behind glass settles within the first 320ms so its paint is stable before the panel reaches its boundary.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'select',
        key: 'panelCollapseEasing',
        label: 'Select: panel close easing',
        options: MOTION_EASING_OPTIONS,
      },
      {
        kind: 'number',
        key: 'listSettleDurationMs',
        label: 'Select: short-list settle-in',
        description: 'How long the collapsed short list takes to fade/slide into its new order once the panel finishes collapsing.',
        min: 0,
        max: 1000,
        step: 10,
        unit: 'ms',
        integer: true,
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/MobilePinnedArticleSection/MobilePinnedArticleSection.config.ts',
      targetSymbol: 'DEFAULT_MOBILE_PINNED_ARTICLE_SECTION_CONFIG',
      targetType: 'MobilePinnedArticleSectionConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });
