import { resolveProceduralColorStackRow } from '../../../helpers/proceduralColorSnapshot';
import type {
  AbstractPaletteCadenceDistribution,
  AbstractPaletteCadenceEasing,
} from '../../../helpers/abstractPaletteCadence';

export type AbstractSkyRenderMode = 'static' | 'living' | 'glass' | 'refractor' | 'legacy';
export type AbstractHeroLayoutMode = 'full' | 'editorial' | 'grid';
export type AbstractSkyInkMode = 'auto' | 'light' | 'dark';
export type AbstractGlassPlayback = 'static' | 'dynamic';
export type AbstractGlassBandOrientation = 'columns' | 'rows';
export type AbstractRefractorOrientation = 'columns' | 'rows';
export type GradientDesignerTarget = 'background' | 'heading';

export type GradientDesignerConfig = {
  skyRenderMode: AbstractSkyRenderMode;
  heroContentEnabled: boolean;
  heroLayoutMode: AbstractHeroLayoutMode;
  editorialSourceRow: number;
  firstRowColorOverrideEnabled: boolean;
  firstRowColorVariation: number;
  firstRowColorSaturation: number;
  firstRowColorBrightness: number;
  firstRowColorHueOffset: number;
  firstRowColorMorph: number;
  firstRowColorShimmer: number;
  firstRowColorPulse: number;
  skySunElevationDeg: number;
  skyStopCount: number;
  skyTurbidity: number;
  skyExposure: number;
  skySaturation: number;
  skyChromaDuck: number;
  skyInkUnity: number;
  skyNightDepth: number;
  skyAfterglow: number;
  skyOzone: number;
  skyFalloff: number;
  skyOriginXPercent: number;
  skyOriginYPercent: number;
  skyRadiusXPercent: number;
  skyRadiusYPercent: number;
  skyMotionSpeed: number;
  skyDriftAmount: number;
  skyBreathAmount: number;
  skyTurbulence: number;
  glassPlayback: AbstractGlassPlayback;
  glassBandOrientation: AbstractGlassBandOrientation;
  glassBandSizePx: number;
  glassDisplacementDeltaPercent: number;
  glassDisplacementDirectionDeg: number;
  glassGradientAngleDeg: number;
  glassGradientColorA: string;
  glassGradientColorB: string;
  glassGradientColorC: string;
  glassGradientColorD: string;
  glassPhase: number;
  glassSpeed: number;
  glassResolution: number;
  glassPauseWhenOffscreen: boolean;
  refractorOrientation: AbstractRefractorOrientation;
  refractorSliceCount: number;
  refractorRowDisplacementStepPercent: number;
  refractorRowScaleStepPercent: number;
  refractorColumnDisplacementStepPercent: number;
  refractorColumnScaleStepPercent: number;
  skyDitherStrength: number;
  skyResolution: number;
  skyPauseWhenOffscreen: boolean;
  skyInkMode: AbstractSkyInkMode;
  heroBackgroundAwarenessEnabled: boolean;
  heroBackgroundAwarenessBrightThreshold: number;
  heroBackgroundAwarenessDarkThreshold: number;
  legacyScrimEnabled: boolean;
  legacyPaletteGuardEnabled: boolean;
  legacyPaletteMaximumYellowCoverage: number;
  legacyPaletteMinimumCounterpointCoverage: number;
  legacyPaletteMinimumHueDiversity: number;
  legacyPaletteMinimumChroma: number;
  legacyPaletteMaximumIntervention: number;
  legacyPaletteLookAheadMs: number;
  legacyPaletteAttackMs: number;
  legacyPaletteReleaseMs: number;
  legacyPaletteCadenceEnabled: boolean;
  legacyPaletteCadenceDistribution: AbstractPaletteCadenceDistribution;
  legacyPaletteCadenceEasing: AbstractPaletteCadenceEasing;
  legacyPaletteCadenceInitialDelayMs: number;
  legacyPaletteCadenceDwellMinMs: number;
  legacyPaletteCadenceDwellMaxMs: number;
  legacyPaletteCadenceTransitionDurationMs: number;
  legacyPaletteCadenceTravel: number;
  legacyPaletteCadenceIdleSpeed: number;
  legacyPaletteCadenceDistributionWidth: number;
  legacyPaletteCadenceInvertedCenterVelocity: number;
  legacyPaletteCadenceInteractionQuietMs: number;
  backgroundColor: string;
  shaderColorSpeed: number;
  shaderColorVariation: number;
  shaderColorSaturation: number;
  shaderColorBrightness: number;
  shaderColorScale: number;
  shaderColorResolution: number;
  shaderColorRandomness: number;
  shaderColorHueOffset: number;
  shaderColorMorph: number;
  shaderColorShimmer: number;
  shaderColorPulse: number;
  gradientFaceCount: number;
  viewZoom: number;
  viewOffsetX: number;
  viewOffsetY: number;
  seed: number;
};

export type AbstractPageGradientConfig = Pick<GradientDesignerConfig,
  | 'skyRenderMode'
  | 'heroContentEnabled'
  | 'heroLayoutMode'
  | 'editorialSourceRow'
  | 'firstRowColorOverrideEnabled'
  | 'firstRowColorVariation'
  | 'firstRowColorSaturation'
  | 'firstRowColorBrightness'
  | 'firstRowColorHueOffset'
  | 'firstRowColorMorph'
  | 'firstRowColorShimmer'
  | 'firstRowColorPulse'
  | 'skySunElevationDeg'
  | 'skyStopCount'
  | 'skyTurbidity'
  | 'skyExposure'
  | 'skySaturation'
  | 'skyChromaDuck'
  | 'skyInkUnity'
  | 'skyNightDepth'
  | 'skyAfterglow'
  | 'skyOzone'
  | 'skyFalloff'
  | 'skyOriginXPercent'
  | 'skyOriginYPercent'
  | 'skyRadiusXPercent'
  | 'skyRadiusYPercent'
  | 'skyMotionSpeed'
  | 'skyDriftAmount'
  | 'skyBreathAmount'
  | 'skyTurbulence'
  | 'glassPlayback'
  | 'glassBandOrientation'
  | 'glassBandSizePx'
  | 'glassDisplacementDeltaPercent'
  | 'glassDisplacementDirectionDeg'
  | 'glassGradientAngleDeg'
  | 'glassGradientColorA'
  | 'glassGradientColorB'
  | 'glassGradientColorC'
  | 'glassGradientColorD'
  | 'glassPhase'
  | 'glassSpeed'
  | 'glassResolution'
  | 'glassPauseWhenOffscreen'
  | 'refractorOrientation'
  | 'refractorSliceCount'
  | 'refractorRowDisplacementStepPercent'
  | 'refractorRowScaleStepPercent'
  | 'refractorColumnDisplacementStepPercent'
  | 'refractorColumnScaleStepPercent'
  | 'skyDitherStrength'
  | 'skyResolution'
  | 'skyPauseWhenOffscreen'
  | 'skyInkMode'
  | 'heroBackgroundAwarenessEnabled'
  | 'heroBackgroundAwarenessBrightThreshold'
  | 'heroBackgroundAwarenessDarkThreshold'
  | 'legacyScrimEnabled'
  | 'legacyPaletteGuardEnabled'
  | 'legacyPaletteMaximumYellowCoverage'
  | 'legacyPaletteMinimumCounterpointCoverage'
  | 'legacyPaletteMinimumHueDiversity'
  | 'legacyPaletteMinimumChroma'
  | 'legacyPaletteMaximumIntervention'
  | 'legacyPaletteLookAheadMs'
  | 'legacyPaletteAttackMs'
  | 'legacyPaletteReleaseMs'
  | 'legacyPaletteCadenceEnabled'
  | 'legacyPaletteCadenceDistribution'
  | 'legacyPaletteCadenceEasing'
  | 'legacyPaletteCadenceInitialDelayMs'
  | 'legacyPaletteCadenceDwellMinMs'
  | 'legacyPaletteCadenceDwellMaxMs'
  | 'legacyPaletteCadenceTransitionDurationMs'
  | 'legacyPaletteCadenceTravel'
  | 'legacyPaletteCadenceIdleSpeed'
  | 'legacyPaletteCadenceDistributionWidth'
  | 'legacyPaletteCadenceInvertedCenterVelocity'
  | 'legacyPaletteCadenceInteractionQuietMs'
  | 'backgroundColor'
  | 'shaderColorSpeed'
  | 'shaderColorVariation'
  | 'shaderColorSaturation'
  | 'shaderColorBrightness'
  | 'shaderColorScale'
  | 'shaderColorResolution'
  | 'shaderColorRandomness'
  | 'shaderColorHueOffset'
  | 'shaderColorMorph'
  | 'shaderColorShimmer'
  | 'shaderColorPulse'
  | 'gradientFaceCount'
  | 'viewZoom'
  | 'viewOffsetX'
  | 'viewOffsetY'
  | 'seed'
>;

export const DEFAULT_ABSTRACT_PAGE_GRADIENT_CONFIG: AbstractPageGradientConfig = {
  skyRenderMode: 'legacy',
  heroContentEnabled: true,
  heroLayoutMode: 'full',
  editorialSourceRow: 3,
  firstRowColorOverrideEnabled: false,
  firstRowColorVariation: 0.185,
  firstRowColorSaturation: 0.64,
  firstRowColorBrightness: 1.09,
  firstRowColorHueOffset: -0.233,
  firstRowColorMorph: 1.45,
  firstRowColorShimmer: 1.17,
  firstRowColorPulse: 1.5,
  skySunElevationDeg: 90,
  skyStopCount: 16,
  skyTurbidity: 10,
  skyExposure: 1.34,
  skySaturation: 1.6,
  skyChromaDuck: 0,
  skyInkUnity: 0.26,
  skyNightDepth: 1,
  skyAfterglow: 0,
  skyOzone: 0,
  skyFalloff: 0.45,
  skyOriginXPercent: 25,
  skyOriginYPercent: -20,
  skyRadiusXPercent: 60,
  skyRadiusYPercent: 180,
  skyMotionSpeed: 0,
  skyDriftAmount: 0,
  skyBreathAmount: 0,
  skyTurbulence: 0,
  glassPlayback: 'static',
  glassBandOrientation: 'columns',
  glassBandSizePx: 18,
  glassDisplacementDeltaPercent: 8,
  glassDisplacementDirectionDeg: 62,
  glassGradientAngleDeg: -24,
  glassGradientColorA: '#4bc7ff',
  glassGradientColorB: '#f22f72',
  glassGradientColorC: '#ff8a4c',
  glassGradientColorD: '#071a3d',
  glassPhase: 0,
  glassSpeed: 0.17,
  glassResolution: 1024,
  glassPauseWhenOffscreen: true,
  refractorOrientation: 'columns',
  refractorSliceCount: 11,
  refractorRowDisplacementStepPercent: 10,
  refractorRowScaleStepPercent: 10,
  refractorColumnDisplacementStepPercent: 10,
  refractorColumnScaleStepPercent: 10,
  skyDitherStrength: 2,
  skyResolution: 768,
  skyPauseWhenOffscreen: true,
  skyInkMode: 'auto',
  heroBackgroundAwarenessEnabled: false,
  heroBackgroundAwarenessBrightThreshold: 0.62,
  heroBackgroundAwarenessDarkThreshold: 0.42,
  legacyScrimEnabled: false,
  legacyPaletteGuardEnabled: true,
  legacyPaletteMaximumYellowCoverage: 0.58,
  legacyPaletteMinimumCounterpointCoverage: 0.12,
  legacyPaletteMinimumHueDiversity: 0.16,
  legacyPaletteMinimumChroma: 0.055,
  legacyPaletteMaximumIntervention: 1,
  legacyPaletteLookAheadMs: 900,
  legacyPaletteAttackMs: 420,
  legacyPaletteReleaseMs: 1400,
  legacyPaletteCadenceEnabled: true,
  legacyPaletteCadenceDistribution: 'gaussian',
  legacyPaletteCadenceEasing: 'sine',
  legacyPaletteCadenceInitialDelayMs: 0,
  legacyPaletteCadenceDwellMinMs: 6000,
  legacyPaletteCadenceDwellMaxMs: 11000,
  legacyPaletteCadenceTransitionDurationMs: 3500,
  legacyPaletteCadenceTravel: 0.42,
  legacyPaletteCadenceIdleSpeed: 0.025,
  legacyPaletteCadenceDistributionWidth: 0.2,
  legacyPaletteCadenceInvertedCenterVelocity: 0.18,
  legacyPaletteCadenceInteractionQuietMs: 2500,
  backgroundColor: '#000000',
  shaderColorSpeed: 2.1,
  shaderColorVariation: 0.185,
  shaderColorSaturation: 0.64,
  shaderColorBrightness: 1.09,
  shaderColorScale: 1.09,
  shaderColorResolution: 768,
  shaderColorRandomness: 0.49,
  shaderColorHueOffset: -0.233,
  shaderColorMorph: 1.45,
  shaderColorShimmer: 1.17,
  shaderColorPulse: 1.5,
  gradientFaceCount: 8,
  viewZoom: 0.8181,
  viewOffsetX: 0.004,
  viewOffsetY: 0.1121,
  seed: 0.556,
};

export const DEFAULT_GRADIENT_DESIGNER_CONFIG: GradientDesignerConfig = {
  ...DEFAULT_ABSTRACT_PAGE_GRADIENT_CONFIG,
};

function formatNumber(value: number, precision = 3) {
  if (!Number.isFinite(value)) return '0';
  return Number(value.toFixed(precision)).toString();
}
export function selectAbstractPageGradientConfig(
  config: GradientDesignerConfig,
): AbstractPageGradientConfig {
  const editorialRow = resolveProceduralColorStackRow(
    config.editorialSourceRow,
    config.gradientFaceCount,
  );

  return {
    skyRenderMode: config.skyRenderMode,
    heroContentEnabled: config.heroContentEnabled,
    heroLayoutMode: config.heroLayoutMode,
    editorialSourceRow: editorialRow.rowNumber,
    firstRowColorOverrideEnabled: config.firstRowColorOverrideEnabled,
    firstRowColorVariation: config.firstRowColorVariation,
    firstRowColorSaturation: config.firstRowColorSaturation,
    firstRowColorBrightness: config.firstRowColorBrightness,
    firstRowColorHueOffset: config.firstRowColorHueOffset,
    firstRowColorMorph: config.firstRowColorMorph,
    firstRowColorShimmer: config.firstRowColorShimmer,
    firstRowColorPulse: config.firstRowColorPulse,
    skySunElevationDeg: config.skySunElevationDeg,
    skyStopCount: config.skyStopCount,
    skyTurbidity: config.skyTurbidity,
    skyExposure: config.skyExposure,
    skySaturation: config.skySaturation,
    skyChromaDuck: config.skyChromaDuck,
    skyInkUnity: config.skyInkUnity,
    skyNightDepth: config.skyNightDepth,
    skyAfterglow: config.skyAfterglow,
    skyOzone: config.skyOzone,
    skyFalloff: config.skyFalloff,
    skyOriginXPercent: config.skyOriginXPercent,
    skyOriginYPercent: config.skyOriginYPercent,
    skyRadiusXPercent: config.skyRadiusXPercent,
    skyRadiusYPercent: config.skyRadiusYPercent,
    skyMotionSpeed: config.skyMotionSpeed,
    skyDriftAmount: config.skyDriftAmount,
    skyBreathAmount: config.skyBreathAmount,
    skyTurbulence: config.skyTurbulence,
    glassPlayback: config.glassPlayback,
    glassBandOrientation: config.glassBandOrientation,
    glassBandSizePx: config.glassBandSizePx,
    glassDisplacementDeltaPercent: config.glassDisplacementDeltaPercent,
    glassDisplacementDirectionDeg: config.glassDisplacementDirectionDeg,
    glassGradientAngleDeg: config.glassGradientAngleDeg,
    glassGradientColorA: config.glassGradientColorA,
    glassGradientColorB: config.glassGradientColorB,
    glassGradientColorC: config.glassGradientColorC,
    glassGradientColorD: config.glassGradientColorD,
    glassPhase: config.glassPhase,
    glassSpeed: config.glassSpeed,
    glassResolution: config.glassResolution,
    glassPauseWhenOffscreen: config.glassPauseWhenOffscreen,
    refractorOrientation: config.refractorOrientation,
    refractorSliceCount: config.refractorSliceCount,
    refractorRowDisplacementStepPercent: config.refractorRowDisplacementStepPercent,
    refractorRowScaleStepPercent: config.refractorRowScaleStepPercent,
    refractorColumnDisplacementStepPercent: config.refractorColumnDisplacementStepPercent,
    refractorColumnScaleStepPercent: config.refractorColumnScaleStepPercent,
    skyDitherStrength: config.skyDitherStrength,
    skyResolution: config.skyResolution,
    skyPauseWhenOffscreen: config.skyPauseWhenOffscreen,
    skyInkMode: config.skyInkMode,
    heroBackgroundAwarenessEnabled: config.heroBackgroundAwarenessEnabled,
    heroBackgroundAwarenessBrightThreshold: config.heroBackgroundAwarenessBrightThreshold,
    heroBackgroundAwarenessDarkThreshold: config.heroBackgroundAwarenessDarkThreshold,
    legacyScrimEnabled: config.legacyScrimEnabled,
    legacyPaletteGuardEnabled: config.legacyPaletteGuardEnabled,
    legacyPaletteMaximumYellowCoverage: config.legacyPaletteMaximumYellowCoverage,
    legacyPaletteMinimumCounterpointCoverage: config.legacyPaletteMinimumCounterpointCoverage,
    legacyPaletteMinimumHueDiversity: config.legacyPaletteMinimumHueDiversity,
    legacyPaletteMinimumChroma: config.legacyPaletteMinimumChroma,
    legacyPaletteMaximumIntervention: config.legacyPaletteMaximumIntervention,
    legacyPaletteLookAheadMs: config.legacyPaletteLookAheadMs,
    legacyPaletteAttackMs: config.legacyPaletteAttackMs,
    legacyPaletteReleaseMs: config.legacyPaletteReleaseMs,
    legacyPaletteCadenceEnabled: config.legacyPaletteCadenceEnabled,
    legacyPaletteCadenceDistribution: config.legacyPaletteCadenceDistribution,
    legacyPaletteCadenceEasing: config.legacyPaletteCadenceEasing,
    legacyPaletteCadenceInitialDelayMs: config.legacyPaletteCadenceInitialDelayMs,
    legacyPaletteCadenceDwellMinMs: config.legacyPaletteCadenceDwellMinMs,
    legacyPaletteCadenceDwellMaxMs: config.legacyPaletteCadenceDwellMaxMs,
    legacyPaletteCadenceTransitionDurationMs: config.legacyPaletteCadenceTransitionDurationMs,
    legacyPaletteCadenceTravel: config.legacyPaletteCadenceTravel,
    legacyPaletteCadenceIdleSpeed: config.legacyPaletteCadenceIdleSpeed,
    legacyPaletteCadenceDistributionWidth: config.legacyPaletteCadenceDistributionWidth,
    legacyPaletteCadenceInvertedCenterVelocity: config.legacyPaletteCadenceInvertedCenterVelocity,
    legacyPaletteCadenceInteractionQuietMs: config.legacyPaletteCadenceInteractionQuietMs,
    backgroundColor: config.backgroundColor,
    shaderColorSpeed: config.shaderColorSpeed,
    shaderColorVariation: config.shaderColorVariation,
    shaderColorSaturation: config.shaderColorSaturation,
    shaderColorBrightness: config.shaderColorBrightness,
    shaderColorScale: config.shaderColorScale,
    shaderColorResolution: config.shaderColorResolution,
    shaderColorRandomness: config.shaderColorRandomness,
    shaderColorHueOffset: config.shaderColorHueOffset,
    shaderColorMorph: config.shaderColorMorph,
    shaderColorShimmer: config.shaderColorShimmer,
    shaderColorPulse: config.shaderColorPulse,
    gradientFaceCount: config.gradientFaceCount,
    viewZoom: config.viewZoom,
    viewOffsetX: config.viewOffsetX,
    viewOffsetY: config.viewOffsetY,
    seed: config.seed,
  };
}
