import { defineConfigScopeRegistry } from '../../components/Panel/config';
import {
  ABSTRACT_LAB_SECTION_APPEARANCE_PANEL,
  ABSTRACT_LAB_SECTION_APPEARANCE_SCOPE_ID,
} from './LabSection.panel';
import {
  ABSTRACT_METAL_LAB_CARD_PANEL,
  ABSTRACT_METAL_LAB_CARD_SCOPE_ID,
} from './components/AbstractMetalLabList.panel';
import {
  ABSTRACT_JOURNAL_LAB_COLLECTION_PANEL,
  ABSTRACT_JOURNAL_LAB_COLLECTION_SCOPE_ID,
} from './components/AbstractJournalLabCollection/config/presentation.panel';
import {
  ABSTRACT_JOURNAL_LAB_COLLECTION_SLIDER_PANEL,
  ABSTRACT_JOURNAL_LAB_COLLECTION_SLIDER_SCOPE_ID,
} from './components/AbstractJournalLabCollection/config/slider.panel';
import {
  CTA_BUTTON_APPEARANCE_PANEL,
  CTA_BUTTON_APPEARANCE_SCOPE_ID,
} from '../../components/CtaButton/config/panel';
import {
  FIBER_HEADING_APPEARANCE_PANEL,
  FIBER_HEADING_APPEARANCE_SCOPE_ID,
} from '../../components/FiberHeading.panel';
import {
  PAGE_SURFACE_APPEARANCE_PANEL,
  PAGE_SURFACE_APPEARANCE_SCOPE_ID,
} from '../../components/PageSurface.panel';
import {
  GLOBAL_TYPOGRAPHY_APPEARANCE_PANEL,
  GLOBAL_TYPOGRAPHY_APPEARANCE_SCOPE_ID,
} from '../../components/GlobalTypography.panel';
import {
  LAYOUT_DEBUG_PANEL,
  LAYOUT_DEBUG_SCOPE_ID,
} from '../../components/LayoutDebug.panel';
import {
  SECTION_HEADING_APPEARANCE_PANEL,
  SECTION_HEADING_APPEARANCE_SCOPE_ID,
} from '../../components/SectionHeading.panel';
import {
  ABSTRACT_EDITORIAL_HERO_LAYOUT_PANEL,
  ABSTRACT_EDITORIAL_HERO_LAYOUT_SCOPE_ID,
} from './components/AbstractEditorialHero.panel';
import {
  SITE_HEADER_COLORS_PANEL,
  SITE_HEADER_COLORS_SCOPE_ID,
} from './components/SiteHeader/config/panel';
import {
  WORDMARK_PANEL,
  WORDMARK_SCOPE_ID,
} from './components/SiteHeader/config/wordmark.panel';
import {
  ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_PANEL,
  ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_SCOPE_ID,
} from './components/AbstractHeroCtaComposer/config/panel';
import {
  ABSTRACT_NARROW_COLUMN_STACK_PANEL,
  ABSTRACT_NARROW_COLUMN_STACK_SCOPE_ID,
  ABSTRACT_PAGE_LAYOUT_PANEL,
  ABSTRACT_PAGE_LAYOUT_SCOPE_ID,
} from '../../pages/abstract.panel';
import {
  SPLIT_COLUMN_CARD_PREVIEW_PANEL,
  SPLIT_COLUMN_CARD_PREVIEW_SCOPE_ID,
} from './components/SplitColumnCardPreview.panel';
import {
  SPLIT_COLUMN_CARD_STACK_PANEL,
  SPLIT_COLUMN_CARD_STACK_SCOPE_ID,
} from './components/SplitColumnCardPreview/config/stack.panel';
import {
  COVER_FLOW_PANEL,
  COVER_FLOW_SCOPE_ID,
} from './components/CoverFlow/CoverFlow.panel';
import {
  ABSTRACT_TIMELINE_PANEL,
  ABSTRACT_TIMELINE_SCOPE_ID,
} from './components/AbstractTimeline.panel';
import {
  ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_PANEL,
  ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_SCOPE_ID,
  ABSTRACT_POST_DOCK_HUE_INFLUENCE_PANEL,
  ABSTRACT_POST_DOCK_HUE_INFLUENCE_SCOPE_ID,
  ABSTRACT_POST_DOCK_INTRODUCTION_PANEL,
  ABSTRACT_POST_DOCK_INTRODUCTION_SCOPE_ID,
  ABSTRACT_POST_DOCK_MESH_GEOMETRY_PANEL,
  ABSTRACT_POST_DOCK_MESH_GEOMETRY_SCOPE_ID,
  ABSTRACT_POST_DOCK_PALETTE_PANEL,
  ABSTRACT_POST_DOCK_PALETTE_SCOPE_ID,
  ABSTRACT_POST_DOCK_LAYOUT_PANEL,
  ABSTRACT_POST_DOCK_LAYOUT_SCOPE_ID,
  ABSTRACT_POST_DOCK_HOLOGRAM_PANEL,
  ABSTRACT_POST_DOCK_HOLOGRAM_SCOPE_ID,
} from './components/AbstractPostDock/config/panel';

// PolymorphicLayout, SiteHeaderColorOverride, and
// CtaButtonColorOverride have no entries here — /abstract owns a complete,
// independent instance of each, imported directly from their own
// component-owned .panel.ts files (ABSTRACT_POLYMORPHIC_LAYOUT_PANEL from
// pages/abstract.panel.ts, ABSTRACT_SITE_HEADER_COLOR_OVERRIDE_PANEL
// from ../../components/SiteHeaderColorOverride.panel.ts,
// ABSTRACT_CTA_BUTTON_COLOR_OVERRIDE_PANEL from
// ../../components/CtaButton/config/colorOverride.panel.ts, each imported
// straight into pages/abstract.tsx) per PLAN-CONFIG-SCOPE-PAGE-OWNERSHIP.md
// — no registry indirection needed for a scope that's already uniquely
// named per page.

export const abstractConfigPanelRegistry = defineConfigScopeRegistry({
  [CTA_BUTTON_APPEARANCE_SCOPE_ID]: CTA_BUTTON_APPEARANCE_PANEL,
  [FIBER_HEADING_APPEARANCE_SCOPE_ID]: FIBER_HEADING_APPEARANCE_PANEL,
  [SECTION_HEADING_APPEARANCE_SCOPE_ID]: SECTION_HEADING_APPEARANCE_PANEL,
  [PAGE_SURFACE_APPEARANCE_SCOPE_ID]: PAGE_SURFACE_APPEARANCE_PANEL,
  [GLOBAL_TYPOGRAPHY_APPEARANCE_SCOPE_ID]: GLOBAL_TYPOGRAPHY_APPEARANCE_PANEL,
  [LAYOUT_DEBUG_SCOPE_ID]: LAYOUT_DEBUG_PANEL,
  [ABSTRACT_EDITORIAL_HERO_LAYOUT_SCOPE_ID]:
    ABSTRACT_EDITORIAL_HERO_LAYOUT_PANEL,
  [SITE_HEADER_COLORS_SCOPE_ID]:
    SITE_HEADER_COLORS_PANEL,
  [WORDMARK_SCOPE_ID]:
    WORDMARK_PANEL,
  [ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_SCOPE_ID]:
    ABSTRACT_HERO_CTA_COMPOSER_ENTRANCE_PANEL,
  [ABSTRACT_POST_DOCK_INTRODUCTION_SCOPE_ID]:
    ABSTRACT_POST_DOCK_INTRODUCTION_PANEL,
  [ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_SCOPE_ID]:
    ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_PANEL,
  [ABSTRACT_POST_DOCK_PALETTE_SCOPE_ID]:
    ABSTRACT_POST_DOCK_PALETTE_PANEL,
  [ABSTRACT_POST_DOCK_MESH_GEOMETRY_SCOPE_ID]:
    ABSTRACT_POST_DOCK_MESH_GEOMETRY_PANEL,
  [ABSTRACT_POST_DOCK_HUE_INFLUENCE_SCOPE_ID]:
    ABSTRACT_POST_DOCK_HUE_INFLUENCE_PANEL,
  [ABSTRACT_POST_DOCK_LAYOUT_SCOPE_ID]:
    ABSTRACT_POST_DOCK_LAYOUT_PANEL,
  [ABSTRACT_POST_DOCK_HOLOGRAM_SCOPE_ID]:
    ABSTRACT_POST_DOCK_HOLOGRAM_PANEL,
  [ABSTRACT_JOURNAL_LAB_COLLECTION_SCOPE_ID]:
    ABSTRACT_JOURNAL_LAB_COLLECTION_PANEL,
  [ABSTRACT_JOURNAL_LAB_COLLECTION_SLIDER_SCOPE_ID]:
    ABSTRACT_JOURNAL_LAB_COLLECTION_SLIDER_PANEL,
  [ABSTRACT_METAL_LAB_CARD_SCOPE_ID]:
    ABSTRACT_METAL_LAB_CARD_PANEL,
  [ABSTRACT_LAB_SECTION_APPEARANCE_SCOPE_ID]:
    ABSTRACT_LAB_SECTION_APPEARANCE_PANEL,
  [ABSTRACT_PAGE_LAYOUT_SCOPE_ID]:
    ABSTRACT_PAGE_LAYOUT_PANEL,
  [ABSTRACT_NARROW_COLUMN_STACK_SCOPE_ID]:
    ABSTRACT_NARROW_COLUMN_STACK_PANEL,
  [SPLIT_COLUMN_CARD_PREVIEW_SCOPE_ID]:
    SPLIT_COLUMN_CARD_PREVIEW_PANEL,
  [SPLIT_COLUMN_CARD_STACK_SCOPE_ID]:
    SPLIT_COLUMN_CARD_STACK_PANEL,
  [COVER_FLOW_SCOPE_ID]:
    COVER_FLOW_PANEL,
  [ABSTRACT_TIMELINE_SCOPE_ID]:
    ABSTRACT_TIMELINE_PANEL,
});
