import { defineConfigScope } from './Panel/config';
import {
  DEFAULT_FIBER_HEADING_CONFIG,
  type FiberHeadingConfig,
} from './FiberHeading.config';

export const FIBER_HEADING_APPEARANCE_SCOPE_ID = 'FiberHeading/appearance' as const;

export const FIBER_HEADING_APPEARANCE_PANEL = defineConfigScope<FiberHeadingConfig>({
  id: FIBER_HEADING_APPEARANCE_SCOPE_ID,
  component: 'FiberHeading',
  scope: 'appearance',
  title: 'Fiber heading',
  createdAt: '2026-07-20',
  summary: 'Shape · border · padding · fill',
  defaultOpen: false,
  defaultValue: DEFAULT_FIBER_HEADING_CONFIG,
  fields: [
    {
      kind: 'group',
      label: 'Shape',
      fields: [
        {
          kind: 'enum',
          key: 'align',
          label: 'Alignment',
          description: 'Where the belly/text sits along the hairline, which always spans the full container width regardless.',
          options: [
            { label: 'LEFT', value: 'left' },
            { label: 'CENTER', value: 'center' },
            { label: 'RIGHT', value: 'right' },
          ],
        },
        {
          kind: 'number',
          key: 'bellyFullness',
          label: 'Belly fullness',
          description: 'Fraction of the container height the belly\'s peak thickness fills.',
          min: 0.05,
          max: 1,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'taperFlatness',
          label: 'Taper flatness (mobile)',
          description: 'Higher = most of the narrowing happens right after the shoulder, leaving a long, nearly-flat glide into the hairline tip. Lower = a more evenly-tapering wedge. Keep this lower than the desktop value — the same curve compressed into a narrower mobile padding margin reads as a sharp corner otherwise. Applies below the md breakpoint (768px).',
          min: 1,
          max: 8,
          step: 0.1,
        },
        {
          kind: 'number',
          key: 'taperFlatnessDesktop',
          label: 'Taper flatness (desktop)',
          description: 'Overrides the mobile value from md (768px) up, where the wider padding margin can carry a higher value without looking sharp.',
          min: 1,
          max: 8,
          step: 0.1,
        },
        {
          kind: 'enum',
          key: 'borderThickness',
          label: 'Border thickness',
          description: 'The full-width hairline\'s own thickness.',
          options: [
            { label: 'HAIRLINE', value: 'hairline' },
            { label: 'THIN', value: 'thin' },
            { label: 'REGULAR', value: 'regular' },
            { label: 'BOLD', value: 'bold' },
          ],
        },
        {
          kind: 'enum',
          key: 'containerHeight',
          label: 'Container height (mobile)',
          description: 'Uses Tailwind height tokens. Applies below the md breakpoint (768px).',
          options: [
            { label: 'h-6', value: 'h-6' },
            { label: 'h-8', value: 'h-8' },
            { label: 'h-10', value: 'h-10' },
            { label: 'h-12', value: 'h-12' },
            { label: 'h-14', value: 'h-14' },
            { label: 'h-16', value: 'h-16' },
            { label: 'h-20', value: 'h-20' },
            { label: 'h-24', value: 'h-24' },
            { label: 'h-28', value: 'h-28' },
            { label: 'h-32', value: 'h-32' },
          ],
        },
        {
          kind: 'enum',
          key: 'containerHeightDesktop',
          label: 'Container height (desktop)',
          description: 'Overrides the mobile height from md (768px) up.',
          options: [
            { label: 'h-6', value: 'md:h-6' },
            { label: 'h-8', value: 'md:h-8' },
            { label: 'h-10', value: 'md:h-10' },
            { label: 'h-12', value: 'md:h-12' },
            { label: 'h-14', value: 'md:h-14' },
            { label: 'h-16', value: 'md:h-16' },
            { label: 'h-20', value: 'md:h-20' },
            { label: 'h-24', value: 'md:h-24' },
            { label: 'h-28', value: 'md:h-28' },
            { label: 'h-32', value: 'md:h-32' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Belly width',
      fields: [
        {
          kind: 'enum',
          key: 'bellyWidthMode',
          label: 'Width mode',
          options: [
            { label: 'AUTO (size to text)', value: 'auto' },
            { label: 'FIXED', value: 'fixed' },
          ],
        },
        {
          kind: 'number',
          key: 'bellyWidthPx',
          label: 'Fixed belly width',
          min: 40,
          max: 1200,
          step: 4,
          unit: 'px',
          integer: true,
          visibleWhen: config => config.bellyWidthMode === 'fixed',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Text',
      fields: [
        {
          kind: 'number',
          key: 'textPaddingXPx',
          label: 'Horizontal padding (mobile)',
          description: 'Also the taper\'s own margin — more padding reads as a gentler swell. Applies below the md breakpoint (768px).',
          min: 0,
          max: 200,
          step: 2,
          unit: 'px',
          integer: true,
        },
        {
          kind: 'number',
          key: 'textPaddingXPxDesktop',
          label: 'Horizontal padding (desktop)',
          description: 'Overrides the mobile padding from md (768px) up.',
          min: 0,
          max: 400,
          step: 2,
          unit: 'px',
          integer: true,
        },
        {
          kind: 'number',
          key: 'textPaddingYPx',
          label: 'Vertical padding (mobile)',
          min: 0,
          max: 120,
          step: 1,
          unit: 'px',
          integer: true,
        },
        {
          kind: 'number',
          key: 'textPaddingYPxDesktop',
          label: 'Vertical padding (desktop)',
          min: 0,
          max: 240,
          step: 1,
          unit: 'px',
          integer: true,
        },
        {
          kind: 'number',
          key: 'letterSpacingEm',
          label: 'Letter spacing',
          min: 0,
          max: 1,
          step: 0.01,
          unit: 'em',
        },
        {
          kind: 'enum',
          key: 'fontSize',
          label: 'Font size (mobile)',
          description: 'Applies below the md breakpoint (768px).',
          options: [
            { label: 'sm', value: 'text-sm' },
            { label: 'base', value: 'text-base' },
            { label: 'lg', value: 'text-lg' },
            { label: 'xl', value: 'text-xl' },
            { label: '2xl', value: 'text-2xl' },
            { label: '3xl', value: 'text-3xl' },
            { label: '4xl', value: 'text-4xl' },
            { label: '5xl', value: 'text-5xl' },
            { label: '6xl', value: 'text-6xl' },
          ],
        },
        {
          kind: 'enum',
          key: 'fontSizeDesktop',
          label: 'Font size (desktop)',
          description: 'Overrides the mobile font size from md (768px) up.',
          options: [
            { label: 'sm', value: 'md:text-sm' },
            { label: 'base', value: 'md:text-base' },
            { label: 'lg', value: 'md:text-lg' },
            { label: 'xl', value: 'md:text-xl' },
            { label: '2xl', value: 'md:text-2xl' },
            { label: '3xl', value: 'md:text-3xl' },
            { label: '4xl', value: 'md:text-4xl' },
            { label: '5xl', value: 'md:text-5xl' },
            { label: '6xl', value: 'md:text-6xl' },
          ],
        },
        {
          kind: 'enum',
          key: 'fontFamily',
          label: 'Heading font',
          description: 'Inherit (default) follows the site-wide Global typography setting. Sans/Serif pin this heading regardless of that setting.',
          options: [
            { label: 'INHERIT', value: 'inherit' },
            { label: 'SANS', value: 'sans' },
            { label: 'SERIF', value: 'serif' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Fill',
      fields: [
        {
          kind: 'enum',
          key: 'fillMode',
          label: 'Belly fill',
          options: [
            { label: 'SOLID', value: 'solid' },
            { label: 'GRADIENT', value: 'gradient' },
          ],
        },
        {
          kind: 'color',
          key: 'solidColor',
          label: 'Belly color',
          visibleWhen: config => config.fillMode === 'solid',
        },
        {
          kind: 'number',
          key: 'gradientScale',
          label: 'Gradient scale',
          min: 1,
          max: 3,
          step: 0.01,
          unit: 'x',
          visibleWhen: config => config.fillMode === 'gradient',
        },
        {
          kind: 'number',
          key: 'gradientPanXPercent',
          label: 'Gradient pan X',
          min: 0,
          max: 100,
          step: 1,
          unit: '%',
          integer: true,
          visibleWhen: config => config.fillMode === 'gradient',
        },
        {
          kind: 'number',
          key: 'gradientPanYPercent',
          label: 'Gradient pan Y',
          min: 0,
          max: 100,
          step: 1,
          unit: '%',
          integer: true,
          visibleWhen: config => config.fillMode === 'gradient',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Text fill',
      fields: [
        {
          kind: 'enum',
          key: 'textFillMode',
          label: 'Text fill',
          description: '\'Inherit\' samples the same painted belly field the text sits on.',
          options: [
            { label: 'INHERIT', value: 'inherit' },
            { label: 'SOLID', value: 'solid' },
          ],
          visibleWhen: config => config.fillMode === 'gradient',
        },
        {
          kind: 'color',
          key: 'textColor',
          label: 'Text color',
          visibleWhen: config => config.fillMode === 'solid' || config.textFillMode === 'solid',
        },
      ],
    },
  ],
  // Named states worth their own generated Storybook story rather than
  // only reachable via the Playground's live Controls — see AGENTS.md's
  // "Storybook (SB8) documentation automation" for what this list is and
  // isn't for.
  documentedStates: [
    {
      name: 'GradientFill',
      description: 'fillMode: gradient — the belly is painted from a live '
        + 'canvas texture rather than a flat CSS color, a structurally '
        + 'different rendering path. Requires a gradientSource decorator '
        + '(see storybookDecorators.tsx) to render correctly; a static '
        + 'config value alone cannot supply the live texture.',
      value: { fillMode: 'gradient' },
    },
  ],
  copy: {
    targetFile: 'components/FiberHeading.config.ts',
    targetSymbol: 'DEFAULT_FIBER_HEADING_CONFIG',
    targetType: 'FiberHeadingConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});
