import { defineConfigScope } from './defineConfigScope';
import {
  DEFAULT_PANEL_SHELL_CONFIG,
  type PanelShellConfig,
} from './shell';

export const PANEL_SHELL_APPEARANCE_SCOPE_ID = 'PanelShell/appearance' as const;

export const PANEL_SHELL_APPEARANCE_PANEL = defineConfigScope<PanelShellConfig>({
  id: PANEL_SHELL_APPEARANCE_SCOPE_ID,
  component: 'PanelShell',
  scope: 'appearance',
  title: 'Config panel',
  createdAt: '2026-08-11',
  summary: 'Inherited surface · hue treatment · translucent blur · derived ink · elevation',
  defaultOpen: false,
  defaultValue: DEFAULT_PANEL_SHELL_CONFIG,
  fields: [
    {
      kind: 'group',
      label: 'Surface',
      fields: [
        {
          kind: 'enum',
          key: 'backgroundColorMode',
          label: 'Background source',
          description: 'Inherited uses the physical rightmost split column, falling back to the page surface. Custom replaces that source.',
          options: [
            { label: 'INHERITED', value: 'inherited' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'color',
          key: 'backgroundColor',
          label: 'Custom background',
          visibleWhen: config => config.backgroundColorMode === 'custom',
        },
        {
          kind: 'number',
          key: 'backgroundOriginalHueRetention',
          label: 'Original hue retention',
          description: 'Preserves a proportion of the source hue while the signed hue shift moves the remainder around the color wheel. A value of 1 keeps the original hue.',
          min: 0,
          max: 1,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'backgroundHueShiftDegrees',
          label: 'Hue shift',
          description: 'Negative and positive values move in opposite directions around the color spectrum. Neutral sources remain neutral.',
          min: -180,
          max: 180,
          step: 1,
          unit: '°',
          integer: true,
        },
        {
          kind: 'number',
          key: 'backgroundPigmentIntensity',
          label: 'Pigment intensity',
          description: 'Scales the source color’s saturation after hue treatment. Zero removes pigment; one preserves it.',
          min: 0,
          max: 2,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'darkBackgroundDarkenRatio',
          label: 'Dark background darkening',
          description: 'Relative lightness reduction applied when the resolved source is dark. A gentler value preserves separation without crushing deep column colors toward black.',
          min: 0,
          max: 0.5,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'lightBackgroundDarkenRatio',
          label: 'Light background darkening',
          description: 'Relative lightness reduction applied when the resolved source is light. This can be stronger so the panel remains visibly distinct from a pale page surface.',
          min: 0,
          max: 0.5,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'nestedSurfaceLightnessStep',
          label: 'Nested accordion depth shading',
          description: 'Darkening applied to a collapsible property zone nested inside a config section (e.g. a Padding/Margin subgroup), so it reads as progressively more "inset" than its own scope. Zero renders it in the same flat fill as the scope around it.',
          min: 0,
          max: 0.16,
          step: 0.01,
        },
        {
          kind: 'number',
          key: 'backgroundOpacity',
          label: 'Panel opacity',
          description: 'Changes only the shell surface paint. Text, controls, separators, and the elevation shadow retain full opacity.',
          min: 0,
          max: 1,
          step: 0.01,
        },
        {
          kind: 'boolean',
          key: 'backgroundBlurEnabled',
          label: 'Internal background blur',
          description: 'Blurs graphics beneath the expanded panel surface while keeping its contents sharp.',
        },
        {
          kind: 'number',
          key: 'backgroundBlurPx',
          label: 'Internal blur strength',
          min: 0,
          max: 48,
          step: 1,
          unit: 'px',
          integer: true,
          visibleWhen: config => config.backgroundBlurEnabled,
        },
        {
          kind: 'boolean',
          key: 'backdropBlurEnabled',
          label: 'Halo blur',
          description: 'Adds a softly feathered blur beyond the panel edge, separate from its internal surface blur.',
        },
        {
          kind: 'number',
          key: 'backdropBlurPx',
          label: 'Halo blur strength',
          min: 0,
          max: 48,
          step: 1,
          unit: 'px',
          integer: true,
          visibleWhen: config => config.backdropBlurEnabled,
        },
        {
          kind: 'number',
          key: 'backdropBlurSafeAreaPx',
          label: 'Halo spread',
          description: 'Extends the non-interactive halo past the panel edge to avoid a hard filter cutoff.',
          min: 0,
          max: 48,
          step: 1,
          unit: 'px',
          integer: true,
          visibleWhen: config => config.backdropBlurEnabled,
        },
        {
          kind: 'number',
          key: 'radiusPx',
          label: 'Corner radius',
          min: 0,
          max: 32,
          step: 1,
          unit: 'px',
          integer: true,
        },
        {
          kind: 'boolean',
          key: 'launcherIconVisible',
          label: 'Show launcher icon',
          description: 'Adds the tune icon beside the SETTINGS label in the collapsed launcher.',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Text',
      fields: [
        {
          kind: 'enum',
          key: 'textColorMode',
          label: 'Text source',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'color',
          key: 'textColor',
          label: 'Custom text color',
          visibleWhen: config => config.textColorMode === 'custom',
        },
        {
          kind: 'number',
          key: 'textMinContrast',
          label: 'Minimum text contrast',
          description: 'Contrast target used when deriving the panel ink from its resolved background.',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.textColorMode === 'auto',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Separators',
      fields: [
        {
          kind: 'enum',
          key: 'separatorColorMode',
          label: 'Separator source',
          description: 'Text derives separator hue from the exact same resolved ink as typography.',
          options: [
            { label: 'TEXT', value: 'text' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'color',
          key: 'separatorColor',
          label: 'Custom separator color',
          visibleWhen: config => config.separatorColorMode === 'custom',
        },
        {
          kind: 'number',
          key: 'separatorOpacity',
          label: 'Section separator opacity',
          min: 0,
          max: 1,
          step: 0.005,
        },
        {
          kind: 'number',
          key: 'internalSeparatorOpacity',
          label: 'Internal separator opacity',
          min: 0,
          max: 1,
          step: 0.005,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Container border',
      fields: [
        {
          kind: 'number',
          key: 'borderWidthPx',
          label: 'Border width',
          min: 0,
          max: 4,
          step: 0.5,
          unit: 'px',
        },
        {
          kind: 'enum',
          key: 'borderColorMode',
          label: 'Border source',
          options: [
            { label: 'TEXT', value: 'text' },
            { label: 'CUSTOM', value: 'custom' },
          ],
          visibleWhen: config => config.borderWidthPx > 0,
        },
        {
          kind: 'color',
          key: 'borderColor',
          label: 'Custom border color',
          visibleWhen: config => (
            config.borderWidthPx > 0 && config.borderColorMode === 'custom'
          ),
        },
        {
          kind: 'number',
          key: 'borderOpacity',
          label: 'Border opacity',
          min: 0,
          max: 1,
          step: 0.01,
          visibleWhen: config => config.borderWidthPx > 0,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Elevation',
      fields: [
        {
          kind: 'boolean',
          key: 'shadowEnabled',
          label: 'Physics shadow',
          description: 'Uses the shared layered elevation-shadow engine; disabling it removes every shell shadow.',
        },
        {
          kind: 'number',
          key: 'restingElevationPx',
          label: 'Resting elevation',
          min: 0,
          max: 20,
          step: 0.5,
          unit: 'px',
          visibleWhen: config => config.shadowEnabled,
        },
        {
          kind: 'number',
          key: 'expandedElevationPx',
          label: 'Expanded elevation',
          min: 0,
          max: 48,
          step: 0.5,
          unit: 'px',
          visibleWhen: config => config.shadowEnabled,
        },
        {
          kind: 'number',
          key: 'shadowElevationMaxPx',
          label: 'Maximum elevation',
          min: 12,
          max: 80,
          step: 1,
          unit: 'px',
          integer: true,
          visibleWhen: config => config.shadowEnabled,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Virtual light',
      visibleWhen: config => config.shadowEnabled,
      fields: [
        { kind: 'number', key: 'shadowLightXPercent', label: 'Light horizontal position', min: 0, max: 100, step: 1, unit: '%' },
        { kind: 'number', key: 'shadowLightYPx', label: 'Light vertical position', min: -600, max: 200, step: 5, unit: 'px' },
        { kind: 'number', key: 'shadowLightHeightPx', label: 'Light height', min: 24, max: 320, step: 2, unit: 'px' },
        { kind: 'number', key: 'shadowLightRadiusPx', label: 'Light radius', min: 8, max: 320, step: 2, unit: 'px' },
        { kind: 'number', key: 'shadowLightDirectIntensity', label: 'Direct intensity', min: 0, max: 4, step: 0.05 },
        { kind: 'number', key: 'shadowLightAmbientIntensity', label: 'Ambient intensity', min: 0, max: 4, step: 0.05 },
      ],
    },
    {
      kind: 'group',
      label: 'Shadow response',
      visibleWhen: config => config.shadowEnabled,
      fields: [
        { kind: 'number', key: 'shadowProjectedStrength', label: 'Projected strength', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'shadowProjectedFalloff', label: 'Projected density falloff', min: 0.2, max: 4, step: 0.05 },
        { kind: 'number', key: 'shadowContactStrength', label: 'Contact strength', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'shadowContactFalloff', label: 'Contact falloff', min: 0.2, max: 4, step: 0.05 },
        { kind: 'number', key: 'shadowContactDecayElevationPx', label: 'Contact decay elevation', min: 4, max: 80, step: 1, unit: 'px' },
        { kind: 'number', key: 'shadowNearFieldStrength', label: 'Near-field strength', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'shadowMaxBlurPx', label: 'Maximum blur', min: 8, max: 160, step: 2, unit: 'px' },
        { kind: 'number', key: 'shadowMaxDisplacementPx', label: 'Maximum displacement', min: 4, max: 100, step: 1, unit: 'px' },
        { kind: 'number', key: 'shadowMaxProjectedScale', label: 'Maximum projected scale', min: 1, max: 1.8, step: 0.01, unit: 'x' },
        {
          kind: 'enum',
          key: 'shadowColorMode',
          label: 'Shadow color source',
          options: [
            { label: 'SURFACE', value: 'surface' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'color',
          key: 'shadowColor',
          label: 'Custom shadow color',
          visibleWhen: config => config.shadowColorMode === 'custom',
        },
        {
          kind: 'number',
          key: 'shadowSurfaceDarkenAmount',
          label: 'Surface shadow darkening',
          min: 0,
          max: 1,
          step: 0.01,
          visibleWhen: config => config.shadowColorMode === 'surface',
        },
      ],
    },
  ],
  copy: {
    targetFile: 'components/Panel/config/shell.ts',
    targetSymbol: 'DEFAULT_PANEL_SHELL_CONFIG',
    targetType: 'PanelShellConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});
