import { describe, expect, it } from 'vitest';
import {
  DEFAULT_PANEL_SHELL_CONFIG,
  normalizePanelShellConfig,
} from './shell';

describe('PanelShell config', () => {
  it('preserves the refined panel defaults', () => {
    expect(DEFAULT_PANEL_SHELL_CONFIG).toMatchObject({
      backgroundColorMode: 'inherited',
      backgroundColor: '#121321',
      darkBackgroundDarkenRatio: 0.34,
      lightBackgroundDarkenRatio: 0.43,
      nestedSurfaceLightnessStep: 0.08,
      backgroundOriginalHueRetention: 0.5,
      backgroundHueShiftDegrees: 6,
      backgroundPigmentIntensity: 0.55,
      backgroundOpacity: 1,
      backgroundBlurEnabled: false,
      backgroundBlurPx: 22,
      backdropBlurEnabled: false,
      backdropBlurPx: 22,
      backdropBlurSafeAreaPx: 16,
      textColorMode: 'auto',
      textColor: '#f5f5f5',
      textMinContrast: 15.4,
      separatorColorMode: 'text',
      separatorColor: '#f5f5f5',
      separatorOpacity: 0.085,
      internalSeparatorOpacity: 0.06,
      borderWidthPx: 0,
      borderColorMode: 'text',
      borderColor: '#f5f5f5',
      borderOpacity: 0.11,
      radiusPx: 12,
      launcherIconVisible: false,
      shadowEnabled: false,
      restingElevationPx: 0,
      expandedElevationPx: 11,
      shadowElevationMaxPx: 20,
      shadowLightXPercent: 100,
      shadowLightYPx: 200,
      shadowLightHeightPx: 40,
      shadowLightRadiusPx: 30,
      shadowLightDirectIntensity: 1.4,
      shadowLightAmbientIntensity: 0.55,
      shadowProjectedStrength: 0.5,
      shadowProjectedFalloff: 2.9,
      shadowContactStrength: 0.12,
      shadowContactFalloff: 0.4,
      shadowContactDecayElevationPx: 50,
      shadowNearFieldStrength: 0.43,
      shadowMaxBlurPx: 30,
      shadowMaxDisplacementPx: 50,
      shadowMaxProjectedScale: 1.11,
      shadowColorMode: 'surface',
      shadowColor: '#0d0d10',
      shadowSurfaceDarkenAmount: 0.24,
    });
  });

  it('normalizes unsafe panel and shadow values through one runtime boundary', () => {
    expect(normalizePanelShellConfig({
      darkBackgroundDarkenRatio: 4,
      lightBackgroundDarkenRatio: -1,
      backgroundOriginalHueRetention: -2,
      backgroundHueShiftDegrees: 400,
      backgroundPigmentIntensity: 4,
      backgroundOpacity: 3,
      backgroundBlurEnabled: false,
      backgroundBlurPx: 90,
      backdropBlurEnabled: false,
      backdropBlurPx: 90,
      backdropBlurSafeAreaPx: -4,
      textMinContrast: 99,
      borderWidthPx: -2,
      radiusPx: 80,
      restingElevationPx: -3,
      expandedElevationPx: 120,
      shadowLightXPercent: 180,
      shadowMaxBlurPx: 2,
      shadowColorMode: 'custom',
      shadowColor: ' ',
    })).toMatchObject({
      darkBackgroundDarkenRatio: 0.5,
      lightBackgroundDarkenRatio: 0,
      backgroundOriginalHueRetention: 0,
      backgroundHueShiftDegrees: 180,
      backgroundPigmentIntensity: 2,
      backgroundOpacity: 1,
      backgroundBlurEnabled: false,
      backgroundBlurPx: 48,
      backdropBlurEnabled: false,
      backdropBlurPx: 48,
      backdropBlurSafeAreaPx: 0,
      textMinContrast: 21,
      borderWidthPx: 0,
      radiusPx: 32,
      restingElevationPx: 0,
      expandedElevationPx: 48,
      shadowLightXPercent: 100,
      shadowMaxBlurPx: 8,
      shadowColorMode: 'custom',
      shadowColor: DEFAULT_PANEL_SHELL_CONFIG.shadowColor,
    });
  });
});
