import { defineConfigScope } from '../components/Panel/config';
import { DEFAULT_CUBE_LAB_CONFIG, type CubeLabConfig } from './cube-lab.config';

export const CUBE_LAB_SCOPE_ID = 'cube-lab/geometry' as const;

export const CUBE_LAB_PANEL = defineConfigScope<CubeLabConfig>({
  id: CUBE_LAB_SCOPE_ID,
  component: 'cube-lab',
  scope: 'geometry',
  title: 'Cube',
  createdAt: '2026-09-10',
  summary: 'Rotate the cuboid parent and tune its perspective',
  defaultOpen: true,
  defaultValue: DEFAULT_CUBE_LAB_CONFIG,
  fields: [
    {
      kind: 'group',
      label: 'Face the camera',
      fields: [
        {
          kind: 'enum',
          key: 'faceTheCameraSelection',
          label: 'Selected face',
          description: 'Selecting a face applies its X/Y preset once. Moving either rotation control afterward immediately returns to manual mode.',
          options: [
            { label: 'NONE (manual)', value: 'none' },
            { label: 'A', value: 'A' },
            { label: 'B', value: 'B' },
            { label: 'C', value: 'C' },
            { label: 'D', value: 'D' },
            { label: 'E', value: 'E' },
            { label: 'F', value: 'F' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Rotation (the cuboid parent only)',
      fields: [
        {
          kind: 'number',
          key: 'rotateXDeg',
          label: 'Rotate X',
          description: 'Freely tips the whole cuboid forward or back. Moving this control clears the selected-face preset automatically.',
          min: -180,
          max: 180,
          step: 1,
          unit: 'deg',
        },
        {
          kind: 'number',
          key: 'rotateYDeg',
          label: 'Rotate Y',
          description: 'Freely spins the whole cuboid left or right. Moving this control clears the selected-face preset automatically.',
          min: -180,
          max: 180,
          step: 1,
          unit: 'deg',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Perspective (the stage, one level up)',
      fields: [
        {
          kind: 'number',
          key: 'perspectivePx',
          label: 'Perspective — windup/turning',
          description: 'CSS perspective, px, set on the stage that wraps the cuboid — never on the cuboid itself (a rotating element must not also own the perspective it is viewed through). Applied for the windup and turning phases of the sequence below (see Sequence group) — the "normal," more dramatic 3D depth used while the structure is actually moving. Lower = stronger foreshortening, higher = flatter.',
          min: 200,
          max: 4000,
          step: 10,
          unit: 'px',
        },
        {
          kind: 'number',
          key: 'landedPerspectivePx',
          label: 'Perspective — settled',
          description: 'The perspective used once fully settled (idle, before windup and after winddown) — deliberately much larger than the windup/turning value above, not smaller/zero: a perspective this far past any face\'s own depth reads as essentially flat/undistorted, which is what keeps a landed face\'s content legible instead of zoomed in (the worst case: Face the camera = A + Fill viewport on, where A\'s own depth can reach 50% of the full viewport width).',
          min: 2000,
          max: 1000000,
          step: 1000,
          unit: 'px',
        },
        {
          kind: 'number',
          key: 'rotationPushBackPx',
          label: 'Z push-back — windup/turning',
          description: 'How far the whole cuboid is pulled away from the camera (world-space, not the cuboid\'s own local Z) during the windup and turning phases only — back to 0 during winddown. See the Sequence group below for the full three-phase order this animates within: push-back and perspective ease OUT first (windup), THEN the rotation itself happens (turning), THEN push-back and perspective ease back IN (winddown) — never simultaneously with the rotation.',
          min: 0,
          max: 4000,
          step: 10,
          unit: 'px',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Size',
      fields: [
        {
          kind: 'boolean',
          key: 'fillViewportEnabled',
          label: 'Fill viewport',
          description: 'Off: the fixed 20vw x 40vw cuboid. On: every face fills the full viewport (100vw x 100dvh) — the scale the real mobile-nav use case actually needs.',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Motion (windup -> turning -> winddown)',
      fields: [
        {
          kind: 'number',
          key: 'rotationDurationMs',
          label: 'Turn duration',
          description: 'Duration for the windup (Z push-back and perspective moving out) and the turn itself. The post-turn landing settle has independent controls below.',
          min: 0,
          max: 3000,
          step: 10,
          unit: 'ms',
        },
        {
          kind: 'enum',
          key: 'rotationEasing',
          label: 'Turn easing',
          description: 'Easing used for the windup and the cuboid rotation. The landing settle uses its own easing below.',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
        {
          kind: 'number',
          key: 'settleDurationMs',
          label: 'Landing settle duration',
          description: 'Duration of the final camera reframe after the destination face reaches its position: Z push-back returns to zero and perspective settles back to its landed value.',
          min: 0,
          max: 5000,
          step: 10,
          unit: 'ms',
        },
        {
          kind: 'enum',
          key: 'settleEasing',
          label: 'Landing settle easing',
          description: 'Easing for the final post-turn reframe. GAUSSIAN starts and ends softly, giving the camera movement a deliberate settle.',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
        {
          kind: 'number',
          key: 'settleOverlapMs',
          label: 'Settle/turn overlap',
          description: '0 (default) keeps windup -> turning -> winddown strictly sequential. Above 0, the landing settle (push-back/perspective easing back in) is allowed to start this many ms before the turn itself finishes, instead of waiting for it — the rotation\'s own duration above is never shortened, only how early the settle is allowed to begin overlaps its tail. Clamped so it can never exceed either the turn duration or the settle duration themselves.',
          min: 0,
          max: 3000,
          step: 10,
          unit: 'ms',
        },
      ],
    },
  ],
  copy: {
    targetFile: 'pages/cube-lab.config.ts',
    targetSymbol: 'DEFAULT_CUBE_LAB_CONFIG',
    targetType: 'CubeLabConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});
