import { defineConfigScope } from '../../../../../components/Panel/config';
import {
  PADDING_TOP_OPTIONS,
  PADDING_TOP_WIDE_OPTIONS,
  PADDING_TOP_LG_OPTIONS,
  PADDING_RIGHT_OPTIONS,
  PADDING_RIGHT_WIDE_OPTIONS,
  PADDING_RIGHT_LG_OPTIONS,
  PADDING_BOTTOM_OPTIONS,
  PADDING_BOTTOM_WIDE_OPTIONS,
  PADDING_BOTTOM_LG_OPTIONS,
  PADDING_LEFT_OPTIONS,
  PADDING_LEFT_WIDE_OPTIONS,
  PADDING_LEFT_LG_OPTIONS,
} from '../../../../../components/tailwindSpacingScale';
import {
  DEFAULT_ABSTRACT_POST_DOCK_INTRODUCTION_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_HUE_INFLUENCE_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_PALETTE_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_MESH_GEOMETRY_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_LAYOUT_CONFIG,
  DEFAULT_ABSTRACT_POST_DOCK_HOLOGRAM_CONFIG,
  type AbstractPostDockGradientPerformanceConfig,
  type AbstractPostDockHueInfluenceConfig,
  type AbstractPostDockIntroductionConfig,
  type AbstractPostDockPaletteConfig,
  type AbstractPostDockMeshGeometryConfig,
  type AbstractPostDockLayoutConfig,
  type AbstractPostDockHologramConfig,
} from './registered';

export const ABSTRACT_POST_DOCK_INTRODUCTION_SCOPE_ID =
  'AbstractPostDock/introduction' as const;

export const ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_SCOPE_ID =
  'AbstractPostDock/gradient-performance' as const;

export const ABSTRACT_POST_DOCK_INTRODUCTION_PANEL =
  defineConfigScope<AbstractPostDockIntroductionConfig>({
    id: ABSTRACT_POST_DOCK_INTRODUCTION_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'introduction',
    title: 'Dock introduction',
    createdAt: '2026-07-13',
    summary: 'Live replay · opacity + directional entry (slider: horizontal · scattered: vertical + excite)',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_INTRODUCTION_CONFIG,
    fields: [
      {
        kind: 'boolean',
        key: 'enabled',
        label: 'Introduction enabled',
        description: 'Opt in to the dock entrance animation.',
      },
      {
        kind: 'enum',
        key: 'mode',
        label: 'Mode',
        options: [
          { label: 'STAG', value: 'stagger' },
          { label: 'SEQ', value: 'sequence' },
        ],
      },
      {
        kind: 'number',
        key: 'firstDelayMs',
        label: 'Start delay',
        min: 0,
        max: 1000,
        step: 20,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'number',
        key: 'durationMs',
        label: 'Duration',
        min: 0,
        max: 1200,
        step: 20,
        unit: 'ms',
        integer: true,
      },
      {
        kind: 'number',
        key: 'staggerMs',
        label: 'Stagger',
        min: 0,
        max: 300,
        step: 10,
        unit: 'ms',
        integer: true,
        visibleWhen: config => config.mode === 'stagger',
      },
      {
        kind: 'number',
        key: 'overlapMs',
        label: 'Sequence overlap',
        description: '0 waits for the current item to finish; higher values overlap adjacent entrances.',
        min: 0,
        max: 1200,
        step: 20,
        unit: 'ms',
        integer: true,
        visibleWhen: config => config.mode === 'sequence',
      },
      {
        kind: 'enum',
        key: 'distribution',
        label: 'Cadence',
        options: [
          { label: 'LIN', value: 'linear' },
          { label: 'GAUSS', value: 'gaussian' },
          { label: 'INV', value: 'gaussian-inverse' },
        ],
      },
      {
        kind: 'number',
        key: 'cadenceAmount',
        label: 'Duration dilation',
        description: "Stretches each item's duration according to its position in the selected cadence curve.",
        min: 0,
        max: 1,
        step: 0.05,
        unit: 'x',
      },
      {
        kind: 'enum',
        key: 'easing',
        label: 'Item easing',
        options: [
          { label: 'STD', value: 'standard' },
          { label: 'EXPO', value: 'soft-expo' },
          { label: 'VISC', value: 'viscous' },
          { label: 'SET', value: 'settle' },
          { label: 'LUX', value: 'luxury' },
        ],
      },
      {
        kind: 'number',
        key: 'offsetXVw',
        label: 'X offset',
        description: 'Slider/deck mode only: horizontal entrance offset.',
        min: -150,
        max: 150,
        step: 5,
        unit: 'vw',
      },
      {
        kind: 'number',
        key: 'offsetYPercent',
        label: 'Y offset',
        description: 'Scattered/grid mode only: how far below rest each card starts, as a % of its own height, before rising into place with a brief tilt + hologram excite.',
        min: 0,
        max: 100,
        step: 5,
        unit: '%',
        integer: true,
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_INTRODUCTION_CONFIG',
      targetType: 'AbstractPostDockIntroductionConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_PANEL =
  defineConfigScope<AbstractPostDockGradientPerformanceConfig>({
    id: ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'gradient-performance',
    title: 'Dock gradient performance',
    createdAt: '2026-07-13',
    summary: 'Render-loop allocation · shared across desktop and mobile',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_CONFIG,
    hiddenKeys: ['activityPolicyNarrow'],
    fields: [
      {
        kind: 'enum',
        key: 'activityPolicy',
        label: 'Gradient activity',
        description: 'Active animates one gradient. All keeps every mounted gradient live. Static never animates.',
        options: [
          { label: 'ACTIVE', value: 'active-only' },
          { label: 'ALL', value: 'all' },
          { label: 'STATIC', value: 'static' },
        ],
      },
      {
        kind: 'boolean',
        key: 'pauseWhenOffscreen',
        label: 'Pause offscreen',
        description: 'Suspend gradient rendering while the dock is outside the viewport.',
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_GRADIENT_PERFORMANCE_CONFIG',
      targetType: 'AbstractPostDockGradientPerformanceConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_PALETTE_SCOPE_ID =
  'AbstractPostDock/palette' as const;

export const ABSTRACT_POST_DOCK_PALETTE_PANEL =
  defineConfigScope<AbstractPostDockPaletteConfig>({
    id: ABSTRACT_POST_DOCK_PALETTE_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'palette',
    title: 'Dock palette direction',
    createdAt: '2026-07-13',
    summary: 'Window: one field, many windows · Chord: LUT experiment',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_PALETTE_CONFIG,
    fields: [
      {
        kind: 'boolean',
        key: 'enabled',
        label: 'Directed palette',
        description: 'Opt in to index-driven palette direction. Off renders the legacy per-slide values.',
      },
      {
        kind: 'enum',
        key: 'mode',
        label: 'Mode',
        description: 'Window keeps the original colours and connects cards through one shared field; Chord replaces the palette (experimental).',
        options: [
          { label: 'WINDOW', value: 'window' },
          { label: 'CHORD', value: 'chord' },
        ],
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'windowStep',
        label: 'Window step',
        description: 'Field offset per card — how far apart the windows are in the shared sky.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'window',
      },
      {
        kind: 'number',
        key: 'hueSpread',
        label: 'Hue spread',
        description: 'Total colour-wheel rotation across the deck (hue-space panorama).',
        min: 0,
        max: 0.72,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'window',
      },
      {
        kind: 'enum',
        key: 'windowPanCurve',
        label: 'Pan curve',
        description: 'Linear (default): even index-proportional pan. Gaussian: pan magnitude bells around one peak card, receding elsewhere.',
        options: [
          { label: 'LINEAR', value: 'linear' },
          { label: 'GAUSSIAN', value: 'gaussian' },
        ],
        visibleWhen: config => config.enabled && config.mode === 'window',
      },
      {
        kind: 'number',
        key: 'gaussianPeakIndex',
        label: 'Gaussian peak index',
        description: 'Real sequence index the bell peaks at (e.g. -1 for a synthetic header slot before index 0).',
        min: -4,
        max: 8,
        step: 1,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'number',
        key: 'gaussianSigma',
        label: 'Gaussian width',
        description: 'Spread of the bell along the sequence — wider values bulge more neighboring cards.',
        min: 0.1,
        max: 6,
        step: 0.1,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'number',
        key: 'gaussianAmplitude',
        label: 'Gaussian amplitude',
        description: 'Peak pan magnitude at the bell center — plays the role Window step plays for the linear curve.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'number',
        key: 'gaussianFloor',
        label: 'Gaussian floor',
        description: 'Minimum retained pan at the quiet tail(s), away from the peak.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'boolean',
        key: 'gaussianVisualTestModeEnabled',
        label: 'Visual test mode',
        description: 'Isolates the Gaussian curve itself: equal card size, equal opacity, value-rig darkening forced off. Chroma ducking stays on — in Gaussian mode it IS the curve\'s own visible saturation bell, not a confound to strip.',
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'boolean',
        key: 'gaussianProximityMorphEnabled',
        label: 'Proximity morph',
        description: 'Off (default): the peak stays fixed. On: each card\'s own live pointer proximity continuously nudges the effective peak toward itself, with no discrete hover snap.',
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian',
      },
      {
        kind: 'number',
        key: 'gaussianProximityResponseMs',
        label: 'Proximity response',
        description: 'Time constant (ms) each card\'s own live-blended offset takes to follow its proximity-derived target.',
        min: 1,
        max: 2000,
        step: 10,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian' && config.gaussianProximityMorphEnabled,
      },
      {
        kind: 'number',
        key: 'gaussianProximityStaggerMsPerBand',
        label: 'Proximity stagger',
        description: 'Extra response time (ms) per unit of index-distance from the nearest hovered card — produces the ripple/cascade read.',
        min: 0,
        max: 500,
        step: 5,
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian' && config.gaussianProximityMorphEnabled,
      },
      {
        kind: 'enum',
        key: 'gaussianProximityEasing',
        label: 'Proximity easing',
        description: 'Distance-falloff curve shaping each card\'s own live proximity signal before it drives the peak shift.',
        options: [
          { label: 'LINEAR', value: 'linear' },
          { label: 'SMOOTHSTEP', value: 'smoothstep' },
          { label: 'SMOOTHERSTEP', value: 'smootherstep' },
          { label: 'EASE-OUT-CUBIC', value: 'ease-out-cubic' },
        ],
        visibleWhen: config => config.enabled && config.mode === 'window' && config.windowPanCurve === 'gaussian' && config.gaussianProximityMorphEnabled,
      },
      {
        kind: 'number',
        key: 'fieldKinship',
        label: 'Field kinship',
        description: '0 = individual field seeds, 1 = one shared field.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'inactiveChromaDuck',
        label: 'Inactive duck',
        description: 'How far cards duck their chroma toward ink — the non-focused row in Linear/Chord mode, or the Gaussian curve\'s own distance-from-peak falloff in Gaussian mode (the visible bell).',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'valueRigAmount',
        label: 'Value rig',
        description: 'Luminance shaping: calm text zones top-left, light lower-right.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'masterSaturation',
        label: 'Master saturation',
        description: 'Master bus: saturation trim on the final colour (1 = neutral).',
        min: 0,
        max: 2,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'masterBrightness',
        label: 'Master brightness',
        description: 'Master bus: brightness trim on the final colour (1 = neutral).',
        min: 0.5,
        max: 1.6,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'masterContrast',
        label: 'Master contrast',
        description: 'Contrast around mid-grey (1 = neutral).',
        min: 0,
        max: 2,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'masterSoftness',
        label: 'Master softness',
        description: 'Extra colour smoothing: widens the shader softness taps and the canvas blur.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      // Gradient scale/noise, tiered by breakpoint (operator ask, 2026-08-25)
      // — same MOBILE/TABLET/DESKTOP tabbed device-size switcher
      // PolymorphicLayout.panel.ts already established
      // (PLAN-POSTS-LAB-PANEL-TABS.md), applied here to just these two
      // fields rather than restructuring this whole flat panel into tabs:
      // every other field in this scope is untiered, so only the two
      // fields that actually need per-breakpoint values get the tab
      // treatment. No "ALL SIZES" tab (unlike PolymorphicLayout's own
      // usage) — there's no untiered content to house there once both
      // fields are split.
      {
        kind: 'tabs',
        tabs: [
          {
            id: 'mobile',
            label: 'MOBILE (< 768px)',
            fields: [
              {
                kind: 'number',
                key: 'gradientScale',
                label: 'Gradient scale',
                description: 'Zoom into the gradient mesh — lower shows more hue variety per card, higher is flatter/more concentrated. Independent of "Directed palette" — a shape/geometry control, not a colour-direction one, so it stays live even with that toggle off.',
                min: 0.5,
                max: 4,
                step: 0.01,
              },
              {
                kind: 'number',
                key: 'gradientNoise',
                label: 'Gradient noise',
                description: 'Amplitude of the gradient mesh\'s own organic domain-warp wobble — 0 is smooth and static, 1 is the full spread. Independent of "Directed palette", same as Gradient scale above.',
                min: 0,
                max: 1,
                step: 0.01,
              },
            ],
          },
          {
            id: 'tablet',
            label: 'TABLET (≥ 768px)',
            fields: [
              {
                kind: 'number',
                key: 'gradientScaleWide',
                label: 'Gradient scale',
                description: 'Same as the Mobile tab\'s own Gradient scale, applied ≥ 768px.',
                min: 0.5,
                max: 4,
                step: 0.01,
              },
              {
                kind: 'number',
                key: 'gradientNoiseWide',
                label: 'Gradient noise',
                description: 'Same as the Mobile tab\'s own Gradient noise, applied ≥ 768px.',
                min: 0,
                max: 1,
                step: 0.01,
              },
            ],
          },
          {
            id: 'desktop',
            label: 'DESKTOP (≥ 1024px)',
            fields: [
              {
                kind: 'number',
                key: 'gradientScaleLg',
                label: 'Gradient scale',
                description: 'Same as the Mobile tab\'s own Gradient scale, applied ≥ 1024px.',
                min: 0.5,
                max: 4,
                step: 0.01,
              },
              {
                kind: 'number',
                key: 'gradientNoiseLg',
                label: 'Gradient noise',
                description: 'Same as the Mobile tab\'s own Gradient noise, applied ≥ 1024px.',
                min: 0,
                max: 1,
                step: 0.01,
              },
            ],
          },
        ],
      },
      {
        kind: 'boolean',
        key: 'distanceDimmingEnabled',
        label: 'Distance dimming',
        description: 'Dims each inactive accordion row with a black overlay by its distance from the active row. Off renders every row at full brightness regardless of distance. Independent of "Directed palette", same as Gradient scale above — a MagnificationDock-level overlay, not a colour-direction control.',
      },
      {
        kind: 'number',
        key: 'distanceDimmingMaxOpacity',
        label: 'Dimming max',
        description: 'Opacity of the black overlay at the farthest inactive row.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.distanceDimmingEnabled,
      },
      {
        kind: 'number',
        key: 'distanceDimmingBaselineOpacity',
        label: 'Dimming baseline',
        description: 'Opacity floor even for the row closest to active — the dimming range is [baseline, max], not [0, max].',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.distanceDimmingEnabled,
      },
      {
        kind: 'number',
        key: 'distanceDimmingPower',
        label: 'Dimming power',
        description: 'Exponent shaping how quickly opacity rises across the [baseline, max] range as distance grows — below 1 front-loads the darkening (reaches near-max quickly, even close to active); above 1 delays it.',
        min: 0.1,
        max: 4,
        step: 0.05,
        visibleWhen: config => config.distanceDimmingEnabled,
      },
      {
        kind: 'enum',
        key: 'distanceDimmingEasing',
        label: 'Dimming easing',
        description: 'Curve shaping normalized distance before the power above applies.',
        options: [
          { label: 'LINEAR', value: 'linear' },
          { label: 'SOFT', value: 'soft' },
          { label: 'EXPO', value: 'expo' },
        ],
        visibleWhen: config => config.distanceDimmingEnabled,
      },
      {
        kind: 'number',
        key: 'rampSpan',
        label: 'Ramp span',
        description: 'Fraction of the spectral ramp the collection traverses.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'rampRotation',
        label: 'Ramp rotation',
        description: 'Base offset along the ramp.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'enum',
        key: 'rampPath',
        label: 'Ramp path',
        description: 'Mirror ping-pongs the ramp (adjacent cards always neighbours); wrap cycles past the ends.',
        options: [
          { label: 'MIRROR', value: 'mirror' },
          { label: 'WRAP', value: 'wrap' },
        ],
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'boolean',
        key: 'relayEnabled',
        label: 'Relay rule',
        description: "Each card's support voice is the next card's dominant — chains the deck.",
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'counterpointChroma',
        label: 'Counterpoint chroma',
        description: 'Chroma cap for the muted opposing voice.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'chordChroma',
        label: 'Chord chroma',
        description: 'Richness: chroma gain baked into the LUT.',
        min: 0,
        max: 2,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'paletteLightness',
        label: 'Palette lightness',
        description: 'Shared tonal register: 0 = ink-dark deck, 1 = airy deck.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'lightnessContrast',
        label: 'Lightness contrast',
        description: 'Value spread within each card cycle.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'inkUnity',
        label: 'Ink unity',
        description: 'Glaze toward one shared ink anchor.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
      {
        kind: 'number',
        key: 'voiceSpread',
        label: 'Voice spread',
        description: 'Intra-voice hue drift across cycle segments.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled && config.mode === 'chord',
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_PALETTE_CONFIG',
      targetType: 'AbstractPostDockPaletteConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_MESH_GEOMETRY_SCOPE_ID =
  'AbstractPostDock/mesh-geometry' as const;

export const ABSTRACT_POST_DOCK_MESH_GEOMETRY_PANEL =
  defineConfigScope<AbstractPostDockMeshGeometryConfig>({
    id: ABSTRACT_POST_DOCK_MESH_GEOMETRY_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'mesh-geometry',
    title: 'Journal mesh geometry',
    createdAt: '2026-07-13',
    summary: 'Geometry-only shaping · preserves source colors and hue grading',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_MESH_GEOMETRY_CONFIG,
    fields: [
      {
        kind: 'boolean',
        key: 'enabled',
        label: 'Enhanced curves',
        description: 'Increases the amplitude of the existing journal mesh without changing its palette.',
      },
      {
        kind: 'number',
        key: 'domainCurveBoost',
        label: 'Curve amplitude',
        description: 'Increases the broad lateral displacement of the existing sampling-domain curves.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'bandCurveBoost',
        label: 'Band curvature',
        description: 'Increases the cross-axis bend of the existing color contours without adding new bands.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_MESH_GEOMETRY_CONFIG',
      targetType: 'AbstractPostDockMeshGeometryConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_HUE_INFLUENCE_SCOPE_ID =
  'AbstractPostDock/hue-influence' as const;

export const ABSTRACT_POST_DOCK_HUE_INFLUENCE_PANEL =
  defineConfigScope<AbstractPostDockHueInfluenceConfig>({
    id: ABSTRACT_POST_DOCK_HUE_INFLUENCE_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'hue-influence',
    title: 'Card hue influence',
    createdAt: '2026-07-13',
    summary: 'Palette-coupled hue family · controlled tonal finish',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_HUE_INFLUENCE_CONFIG,
    fields: [
      {
        kind: 'boolean',
        key: 'enabled',
        label: 'Hue influence',
        description: 'Opt in to a final perceptual hue grade. Off preserves the current card renderer exactly.',
      },
      {
        kind: 'group',
        label: 'Blend and hue',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'number',
            key: 'gradeMix',
            label: 'Grade mix',
            description: 'Blends from the standard field into the configured perceptual grade.',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            kind: 'color',
            key: 'targetColor',
            label: 'Target hue',
            description: 'Uses hue only; brightness is controlled separately by the influenced finish.',
          },
          {
            kind: 'number',
            key: 'hueTrimDegrees',
            label: 'Hue trim',
            description: 'Fine adjustment around the selected target hue.',
            min: -45,
            max: 45,
            step: 0.5,
            unit: '°',
          },
          {
            kind: 'number',
            key: 'paletteHueCoupling',
            label: 'Palette coupling',
            description: 'Carries the Dock palette’s centered per-card direction as a bounded ±24° accent around the selected hue family.',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            kind: 'number',
            key: 'strength',
            label: 'Hue convergence',
            description: 'Narrows the source hue distribution toward the selected hue family.',
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Chroma shaping',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'number',
            key: 'chromaScale',
            label: 'Global chroma',
            description: 'Scales source chroma before automatic in-gamut compression.',
            min: 0,
            max: 1.75,
            step: 0.01,
            unit: 'x',
          },
          {
            kind: 'number',
            key: 'shadowChromaScale',
            label: 'Shadow chroma',
            description: 'Relative chroma retained in darker regions.',
            min: 0,
            max: 2,
            step: 0.01,
            unit: 'x',
          },
          {
            kind: 'number',
            key: 'highlightChromaScale',
            label: 'Highlight chroma',
            description: 'Relative chroma retained in lighter regions.',
            min: 0,
            max: 2,
            step: 0.01,
            unit: 'x',
          },
          {
            kind: 'number',
            key: 'chromaPivot',
            label: 'Chroma pivot',
            description: 'OKLab lightness where shadow and highlight chroma meet.',
            min: 0.15,
            max: 0.85,
            step: 0.01,
          },
          {
            kind: 'number',
            key: 'neutralRecovery',
            label: 'Neutral recovery',
            description: 'Sets a smooth target-derived minimum chroma for gray-prone midtones.',
            min: 0,
            max: 1,
            step: 0.01,
          },
          {
            kind: 'number',
            key: 'neutralThreshold',
            label: 'Neutral threshold',
            description: 'Source-chroma range where hue and counterpoint stabilize toward the target.',
            min: 0.01,
            max: 0.2,
            step: 0.005,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Influenced finish',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'number',
            key: 'tonalRegister',
            label: 'Tonal register',
            description: 'Negative moves the influenced state toward ink; positive makes it airier.',
            min: -1,
            max: 1,
            step: 0.01,
          },
          {
            kind: 'number',
            key: 'lightnessContrast',
            label: 'Lightness contrast',
            description: 'Perceptual value contrast applied only as the grade fades in.',
            min: 0.5,
            max: 1.5,
            step: 0.01,
            unit: 'x',
          },
          {
            kind: 'number',
            key: 'inkUnity',
            label: 'Ink unity',
            description: 'Pulls lightness and chroma toward the shared Abstract ink anchor without replacing the target hue.',
            min: 0,
            max: 1,
            step: 0.01,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Source counterpoint',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'number',
            key: 'counterpointWidthDegrees',
            label: 'Band reach',
            description: 'Hue-space reach of the protected source-color band.',
            min: 0,
            max: 120,
            step: 0.5,
            unit: '°',
          },
          {
            kind: 'number',
            key: 'counterpointFalloff',
            label: 'Band focus',
            description: 'Higher values concentrate source color into a narrower core.',
            min: 0.5,
            max: 10,
            step: 0.25,
          },
          {
            kind: 'number',
            key: 'counterpointChromaScale',
            label: 'Band chroma',
            description: 'Chroma multiplier for the protected source-color voice.',
            min: 0,
            max: 1.5,
            step: 0.01,
            unit: 'x',
          },
          {
            kind: 'number',
            key: 'counterpointChromaFloor',
            label: 'Band fill',
            description: 'Target-relative minimum chroma carried by the expanded band.',
            min: 0,
            max: 1.25,
            step: 0.01,
            unit: 'x',
          },
        ],
      },
      {
        kind: 'group',
        label: 'Transition',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'boolean',
            key: 'transitionEnabled',
            label: 'Smooth transitions',
            description: 'Animates standard/influenced changes and live color tuning.',
          },
          {
            kind: 'number',
            key: 'transitionDurationMs',
            label: 'Toggle duration',
            description: 'Duration for entering or leaving the influenced state.',
            min: 120,
            max: 2400,
            step: 20,
            unit: 'ms',
            visibleWhen: config => config.transitionEnabled,
          },
          {
            kind: 'number',
            key: 'tuningResponseMs',
            label: 'Tuning response',
            description: 'Short response used while adjusting color controls live.',
            min: 40,
            max: 600,
            step: 10,
            unit: 'ms',
            visibleWhen: config => config.transitionEnabled,
          },
          {
            kind: 'enum',
            key: 'transitionEasing',
            label: 'Easing',
            description: 'Motion curve used for grade transitions.',
            options: [
              { label: 'STANDARD', value: 'standard' },
              { label: 'SOFT EXPO', value: 'soft-expo' },
              { label: 'VISCOUS', value: 'viscous' },
              { label: 'SETTLE', value: 'settle' },
              { label: 'LUXURY', value: 'luxury' },
            ],
            visibleWhen: config => config.transitionEnabled,
          },
        ],
      },
      {
        kind: 'group',
        label: 'Output',
        visibleWhen: config => config.enabled,
        fields: [
          {
            kind: 'number',
            key: 'ditherStrength',
            label: 'Dither',
            description: 'Stable, non-animated output dither for dark-blue banding.',
            min: 0,
            max: 1,
            step: 0.01,
            unit: 'LSB',
          },
        ],
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_HUE_INFLUENCE_CONFIG',
      targetType: 'AbstractPostDockHueInfluenceConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_LAYOUT_SCOPE_ID =
  'AbstractPostDock/layout' as const;

export const ABSTRACT_POST_DOCK_LAYOUT_PANEL =
  defineConfigScope<AbstractPostDockLayoutConfig>({
    id: ABSTRACT_POST_DOCK_LAYOUT_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'layout',
    title: 'Dock layout',
    createdAt: '2026-07-13',
    summary: 'Slider (default) vs. scattered card field on wide viewports',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_LAYOUT_CONFIG,
    fields: [
      {
        kind: 'enum',
        key: 'mode',
        label: 'Mode',
        description: 'Scattered replaces the single active slide with every item shown at once, scattered and rotated. Narrow viewports always keep the slider/deck regardless of this setting.',
        options: [
          { label: 'SLIDER', value: 'slider' },
          { label: 'SCATTERED', value: 'scattered' },
        ],
      },
      {
        kind: 'enum',
        key: 'orientation',
        label: 'Orientation',
        description: 'Slider mode only — the axis the active-card magnification travels along.',
        options: [
          { label: 'HORIZONTAL', value: 'horizontal' },
          { label: 'VERTICAL', value: 'vertical' },
        ],
        visibleWhen: config => config.mode === 'slider',
      },
      {
        kind: 'number',
        key: 'cardWidthPx',
        label: 'Card width',
        description: 'Wrapper width per card; height follows at a 3:4 ratio.',
        min: 160,
        max: 480,
        step: 8,
        unit: 'px',
        integer: true,
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'number',
        key: 'columnGapPx',
        label: 'Column gap',
        min: 0,
        max: 96,
        step: 4,
        unit: 'px',
        integer: true,
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'number',
        key: 'rowGapPx',
        label: 'Row gap',
        min: 0,
        max: 128,
        step: 4,
        unit: 'px',
        integer: true,
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'number',
        key: 'maxRotationDeg',
        label: 'Max rotation',
        description: 'Symmetric ± range for each card\'s static resting rotation.',
        min: 0,
        max: 20,
        step: 0.5,
        unit: 'deg',
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'enum',
        key: 'distribution',
        label: 'Distribution',
        description: 'Randomized jitters each card within its row slot (see the two jitter knobs below). Grid places one card per cell, in order — opt in for a predictable reading order instead.',
        options: [
          { label: 'RANDOM', value: 'randomized' },
          { label: 'GRID', value: 'grid' },
        ],
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'number',
        key: 'columnJitterPercent',
        label: 'Column jitter',
        description: 'How far a card may wander horizontally from its slot, as a % of the safe range (never enough to reach a neighbour, rotation included).',
        min: 0,
        max: 100,
        step: 5,
        unit: '%',
        integer: true,
        visibleWhen: config => config.mode === 'scattered' && config.distribution === 'randomized',
      },
      {
        kind: 'number',
        key: 'rowJitterPercent',
        label: 'Row jitter',
        description: 'Same, vertically within the row.',
        min: 0,
        max: 100,
        step: 5,
        unit: '%',
        integer: true,
        visibleWhen: config => config.mode === 'scattered' && config.distribution === 'randomized',
      },
      {
        kind: 'number',
        key: 'topPeekPercent',
        label: 'Top peek',
        description: 'How far the first row extends up past the field\'s own top edge, as a % of one card\'s height — the deck peeking up from behind the heading above it.',
        min: 0,
        max: 20,
        step: 1,
        unit: '%',
        integer: true,
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'number',
        key: 'headingOffsetPx',
        label: 'Heading offset',
        description: 'Space between the hero section and the heading above the cards. 0 lets it (and the deck peeking above it) show above the fold on load; raise it to push the journal section back below the fold.',
        min: 0,
        max: 160,
        step: 4,
        unit: 'px',
        integer: true,
        visibleWhen: config => config.mode === 'scattered',
      },
      {
        kind: 'boolean',
        key: 'minimalModeEnabled',
        label: 'Minimal mode',
        description: 'Scattered: empty cards (Editorial Hero\'s surface color) instead of the article content — position, rotation, and lift/shadow physics are unchanged. Slider: each item\'s own accent color as a solid background with its title shown large, instead of the gradient card.',
        visibleWhen: config => config.mode === 'scattered' || config.mode === 'slider',
      },
      {
        kind: 'boolean',
        key: 'minimalModeGradientEnabled',
        label: 'Minimal mode gradient',
        description: 'Slider minimal mode only: replaces the flat accent-color fill with the same dynamic procedural gradient the full article cards use, sliced across the slides via the palette\'s window-mode index offsets. Off keeps the flat color.',
        visibleWhen: config => config.mode === 'slider' && config.minimalModeEnabled,
      },
      // Minimal mode text size + content padding, tiered by breakpoint
      // (operator ask) — same MOBILE/TABLET/DESKTOP tabbed device-size
      // switcher the palette panel's own gradientScale/gradientNoise tabs
      // already established (AbstractPostDockPaletteConfig, this same
      // config-panel system), applied here to just these two properties
      // rather than restructuring this whole flat panel into tabs: every
      // other field in this scope stays untiered. No "ALL SIZES" tab (same
      // reasoning as the palette panel's own gradient tabs) — there's no
      // untiered content to house there once both properties are split.
      {
        kind: 'tabs',
        visibleWhen: config => config.mode === 'slider' && config.minimalModeEnabled,
        tabs: [
          {
            id: 'mobile',
            label: 'MOBILE (< 768px)',
            fields: [
              {
                kind: 'select',
                key: 'minimalModeFontSize',
                label: 'Text size',
                description: 'Slider minimal mode only — Tailwind\'s own text-size scale. This branch never renders below 768px (narrow viewports route to AbstractDeckSwiper instead) — this tier is the floor TABLET/DESKTOP inherit from unless they override it.',
                options: [
                  { label: 'text-sm', value: 'text-sm' },
                  { label: 'text-base', value: 'text-base' },
                  { label: 'text-lg', value: 'text-lg' },
                  { label: 'text-xl', value: 'text-xl' },
                  { label: 'text-2xl', value: 'text-2xl' },
                  { label: 'text-3xl', value: 'text-3xl' },
                  { label: 'text-4xl', value: 'text-4xl' },
                ],
              },
              { kind: 'select', key: 'minimalModeContentPaddingTop', label: 'Content padding top', options: PADDING_TOP_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingRight', label: 'Content padding right', options: PADDING_RIGHT_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingBottom', label: 'Content padding bottom', options: PADDING_BOTTOM_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingLeft', label: 'Content padding left', options: PADDING_LEFT_OPTIONS },
            ],
          },
          {
            id: 'tablet',
            label: 'TABLET (≥ 768px)',
            fields: [
              {
                kind: 'select',
                key: 'minimalModeFontSizeWide',
                label: 'Text size',
                description: 'Same as the Mobile tab\'s own Text size, applied ≥ 768px.',
                options: [
                  { label: 'md:text-sm', value: 'md:text-sm' },
                  { label: 'md:text-base', value: 'md:text-base' },
                  { label: 'md:text-lg', value: 'md:text-lg' },
                  { label: 'md:text-xl', value: 'md:text-xl' },
                  { label: 'md:text-2xl', value: 'md:text-2xl' },
                  { label: 'md:text-3xl', value: 'md:text-3xl' },
                  { label: 'md:text-4xl', value: 'md:text-4xl' },
                ],
              },
              { kind: 'select', key: 'minimalModeContentPaddingTopWide', label: 'Content padding top', options: PADDING_TOP_WIDE_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingRightWide', label: 'Content padding right', options: PADDING_RIGHT_WIDE_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingBottomWide', label: 'Content padding bottom', options: PADDING_BOTTOM_WIDE_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingLeftWide', label: 'Content padding left', options: PADDING_LEFT_WIDE_OPTIONS },
            ],
          },
          {
            id: 'desktop',
            label: 'DESKTOP (≥ 1024px)',
            fields: [
              {
                kind: 'select',
                key: 'minimalModeFontSizeLg',
                label: 'Text size',
                description: 'Same as the Mobile tab\'s own Text size, applied ≥ 1024px.',
                options: [
                  { label: 'lg:text-sm', value: 'lg:text-sm' },
                  { label: 'lg:text-base', value: 'lg:text-base' },
                  { label: 'lg:text-lg', value: 'lg:text-lg' },
                  { label: 'lg:text-xl', value: 'lg:text-xl' },
                  { label: 'lg:text-2xl', value: 'lg:text-2xl' },
                  { label: 'lg:text-3xl', value: 'lg:text-3xl' },
                  { label: 'lg:text-4xl', value: 'lg:text-4xl' },
                ],
              },
              { kind: 'select', key: 'minimalModeContentPaddingTopLg', label: 'Content padding top', options: PADDING_TOP_LG_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingRightLg', label: 'Content padding right', options: PADDING_RIGHT_LG_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingBottomLg', label: 'Content padding bottom', options: PADDING_BOTTOM_LG_OPTIONS },
              { kind: 'select', key: 'minimalModeContentPaddingLeftLg', label: 'Content padding left', options: PADDING_LEFT_LG_OPTIONS },
            ],
          },
        ],
      },
      {
        kind: 'number',
        key: 'minimalModeTextDimOpacity',
        label: 'Minimal mode text opacity',
        description: 'Slider minimal mode only: opacity for a slide\'s title text outside `**emphasized**` runs.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.mode === 'slider' && config.minimalModeEnabled,
      },
      {
        kind: 'number',
        key: 'minimalModeTextEmphasisOpacity',
        label: 'Minimal mode emphasis opacity',
        description: 'Slider minimal mode only: opacity for `**emphasized**` runs within a slide\'s title text.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.mode === 'slider' && config.minimalModeEnabled,
      },
      {
        kind: 'select',
        key: 'minimalModeTextMaxWidth',
        label: 'Minimal mode text max width',
        description: 'Slider minimal mode only: caps a slide\'s title text to a readable line length — Tailwind\'s own max-width scale.',
        options: [
          { label: 'max-w-sm', value: 'max-w-sm' },
          { label: 'max-w-md', value: 'max-w-md' },
          { label: 'max-w-lg', value: 'max-w-lg' },
          { label: 'max-w-xl', value: 'max-w-xl' },
          { label: 'max-w-2xl', value: 'max-w-2xl' },
          { label: 'max-w-prose', value: 'max-w-prose' },
          { label: 'none', value: 'max-w-none' },
        ],
        visibleWhen: config => config.mode === 'slider' && config.minimalModeEnabled,
      },
      {
        kind: 'boolean',
        key: 'descriptionVisible',
        label: 'Description',
        description: 'Shows the excerpt below the title. Off hides it entirely (title only) — the title\'s own position doesn\'t shift when this is toggled.',
        visibleWhen: config => config.mode === 'scattered' && !config.minimalModeEnabled,
      },
      {
        kind: 'boolean',
        key: 'descriptionHoverReveal',
        label: 'Description on hover',
        description: 'Hides the description until the card is hovered or focused, fading it in/out with the same easing/duration as the "Read article" CTA reveal. Off shows it permanently.',
        visibleWhen: config => config.mode === 'scattered' && !config.minimalModeEnabled && config.descriptionVisible,
      },
      {
        kind: 'enum',
        key: 'cardRadius',
        label: 'Corner radius',
        description: 'Uses Tailwind radius tokens. Applies to the scattered grid and the narrow/touch deck alike.',
        options: [
          { label: 'none', value: 'rounded-none' },
          { label: 'md', value: 'rounded-md' },
          { label: 'lg', value: 'rounded-lg' },
          { label: 'xl', value: 'rounded-xl' },
          { label: '2xl', value: 'rounded-2xl' },
          { label: 'full', value: 'rounded-full' },
        ],
      },
      {
        kind: 'number',
        key: 'peekGapPx',
        label: 'Peek gap',
        description: 'Narrow/touch deck only: separation between the active card and its peeking neighbors. Eats into the peek margin rather than shrinking the active card.',
        min: 0,
        max: 32,
        step: 1,
        unit: 'px',
        integer: true,
      },
      {
        kind: 'boolean',
        key: 'peekDimmingEnabled',
        label: 'Peek dimming',
        description: 'Narrow/touch deck only: dims peeking neighbor cards toward black. Off by default — reads as a hard brightness edge at the card seam.',
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_LAYOUT_CONFIG',
      targetType: 'AbstractPostDockLayoutConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });

export const ABSTRACT_POST_DOCK_HOLOGRAM_SCOPE_ID =
  'AbstractPostDock/hologram' as const;

export const ABSTRACT_POST_DOCK_HOLOGRAM_PANEL =
  defineConfigScope<AbstractPostDockHologramConfig>({
    id: ABSTRACT_POST_DOCK_HOLOGRAM_SCOPE_ID,
    component: 'AbstractPostDock',
    scope: 'hologram',
    title: 'Card tilt hologram',
    createdAt: '2026-07-13',
    summary: 'Tilt reshapes each card\'s own gradient — pointer hover on the scattered grid, swipe drag on the narrow/touch deck',
    defaultOpen: false,
    defaultValue: DEFAULT_ABSTRACT_POST_DOCK_HOLOGRAM_CONFIG,
    fields: [
      {
        kind: 'boolean',
        key: 'enabled',
        label: 'Hologram response',
        description: 'Ties each card\'s gradient offset/hue/saturation/brightness to its own tilt signal (pointer hover on the grid, swipe drag on the deck).',
      },
      {
        kind: 'number',
        key: 'offsetGain',
        label: 'Offset gain',
        description: 'Strength of the gradient pan driven by tilt.',
        min: 0,
        max: 3,
        step: 0.05,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'hueShiftAmount',
        label: 'Hue shift',
        description: 'Max hue rotation at full tilt (same unit as the dock\'s own hue offset).',
        min: 0,
        max: 0.4,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'saturationBoost',
        label: 'Saturation boost',
        description: 'Extra saturation at full tilt.',
        min: 0,
        max: 1,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'brightnessBoost',
        label: 'Brightness boost',
        description: 'Extra brightness at full tilt — the "catching the light" flash.',
        min: 0,
        max: 0.8,
        step: 0.01,
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'enum',
        key: 'responseEasing',
        label: 'Response curve',
        description: 'Shapes tilt magnitude before it drives the gradient response.',
        options: [
          { label: 'LINEAR', value: 'linear' },
          { label: 'SMOOTH', value: 'smoothstep' },
          { label: 'SMOOTHER', value: 'smootherstep' },
          { label: 'EXPO', value: 'ease-out-cubic' },
        ],
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'boolean',
        key: 'dampingEnabled',
        label: 'Damped response',
        description: 'Smooths the hologram in and out with an attack/release envelope on the live proximity signal, symmetric for approach and departure.',
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'boolean',
        key: 'touchDragEnabled',
        label: 'Touch drag response',
        description: 'Touch\'s own equivalent of cursor-proximity tilt — while a finger is on a card, its position drives the hologram the same way a mouse would. Never affects lift/tilt/shadow, only the gradient.',
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'boolean',
        key: 'ambientSweepEnabled',
        label: 'Ambient sweep (touch)',
        description: 'A one-time, scripted hologram sweep for hover-incapable devices — the passive introduction before any real touch. Ignored on hover-capable devices, which keep the live cursor-proximity hologram.',
        visibleWhen: config => config.enabled,
      },
      {
        kind: 'number',
        key: 'ambientSweepStartMs',
        label: 'Ambient sweep delay',
        description: 'Wait from the card first becoming visible to when the sweep actually starts — lets it clear the stack\'s own initial mount/paint, or just read as a deliberate beat rather than an instant reaction to scrolling into view.',
        min: 0,
        max: 5000,
        step: 100,
        unit: 'ms',
        integer: true,
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'number',
        key: 'ambientSweepDurationMs',
        label: 'Ambient sweep duration',
        min: 200,
        max: 4000,
        step: 100,
        unit: 'ms',
        integer: true,
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'enum',
        key: 'ambientSweepEasing',
        label: 'Ambient sweep curve',
        options: [
          { label: 'STANDARD', value: 'standard' },
          { label: 'SOFT EXPO', value: 'soft-expo' },
          { label: 'VISCOUS', value: 'viscous' },
          { label: 'SETTLE', value: 'settle' },
          { label: 'LUXURY', value: 'luxury' },
        ],
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'enum',
        key: 'ambientSweepGeometry',
        label: 'Ambient sweep geometry',
        description: 'Linear: the highlight only ever nudges toward one side and back. Circular: it orbits the card, crossing the full range on both axes — the hue/saturation/brightness response only ever reads the horizontal axis, so circular reads as far more noticeable.',
        options: [
          { label: 'LINEAR', value: 'linear' },
          { label: 'CIRCULAR', value: 'circular' },
        ],
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'number',
        key: 'ambientSweepRadius',
        label: 'Ambient sweep orbit radius',
        description: 'Circular geometry only — how far the orbit reaches, as a fraction of the card\'s full -1..1 tilt range.',
        min: 0,
        max: 1,
        step: 0.05,
        visibleWhen: config => config.enabled && config.ambientSweepEnabled && config.ambientSweepGeometry === 'circular',
      },
      {
        kind: 'number',
        key: 'ambientSweepLoopCount',
        label: 'Ambient sweep revolutions',
        description: 'Circular geometry only — how many full orbits over the sweep\'s own duration.',
        min: 0.5,
        max: 5,
        step: 0.5,
        visibleWhen: config => config.enabled && config.ambientSweepEnabled && config.ambientSweepGeometry === 'circular',
      },
      {
        kind: 'enum',
        key: 'ambientSweepEnvelopeShape',
        label: 'Ambient sweep intensity curve',
        description: 'Gaussian: one smooth peak mid-sweep. Inverse Gaussian: two smaller pulses near the start and end with a dip in the middle. Independent of geometry above — this governs how strong, geometry governs which direction.',
        options: [
          { label: 'GAUSSIAN', value: 'gaussian' },
          { label: 'INVERSE GAUSSIAN', value: 'inverse-gaussian' },
        ],
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'boolean',
        key: 'ambientTiltEnabled',
        label: 'Ambient sweep tilt',
        description: 'An additional physical rotateX/rotateY tilt on the card, driven by the exact same geometry/timing as the ambient sweep\'s gradient — reads as the card physically catching the light rather than only the gradient reacting.',
        visibleWhen: config => config.enabled && config.ambientSweepEnabled,
      },
      {
        kind: 'number',
        key: 'ambientTiltMaxDegrees',
        label: 'Ambient sweep tilt amount',
        min: 0,
        max: 25,
        step: 1,
        unit: 'deg',
        integer: true,
        visibleWhen: config => config.enabled && config.ambientSweepEnabled && config.ambientTiltEnabled,
      },
    ],
    copy: {
      targetFile: 'experiences/abstract/components/AbstractPostDock/config/registered.ts',
      targetSymbol: 'DEFAULT_ABSTRACT_POST_DOCK_HOLOGRAM_CONFIG',
      targetType: 'AbstractPostDockHologramConfig',
      updateStrategy: 'replace_scope',
      completeScope: true,
    },
  });
