import { defineConfigScope } from '../../components/Panel/config';
import {
  FONT_SIZE_OPTIONS, MD_FONT_SIZE_OPTIONS, LG_FONT_SIZE_OPTIONS,
  LEADING_OPTIONS, MD_LEADING_OPTIONS, LG_LEADING_OPTIONS,
  FONT_WEIGHT_OPTIONS,
} from '../../components/tailwindTypographyScale';
import { PADDING_X_OPTIONS, PADDING_Y_OPTIONS, MARGIN_TOP_OPTIONS } from '../../components/tailwindSpacingScale';
import {
  DEFAULT_CONTACT_EXPERIENCE_CONFIG,
  CONTACT_BUTTON_FONT_WEIGHT_WIDE_OPTIONS,
  CONTACT_BUTTON_FONT_WEIGHT_LG_OPTIONS,
  type ContactExperienceConfig,
} from './ContactExperience.config';

export const CONTACT_EXPERIENCE_SCOPE_ID = 'ContactExperience/layout-and-feedback' as const;

export const CONTACT_EXPERIENCE_PANEL = defineConfigScope<ContactExperienceConfig>({
  id: CONTACT_EXPERIENCE_SCOPE_ID,
  component: 'ContactExperience',
  scope: 'layout-and-feedback',
  title: 'Contact experience',
  createdAt: '2026-07-15',
  summary: 'Composition · typography · rhythm · response feedback',
  defaultOpen: true,
  defaultValue: DEFAULT_CONTACT_EXPERIENCE_CONFIG,
  fields: [
    {
      kind: 'group',
      label: 'Composition',
      fields: [
        { kind: 'number', key: 'conversationMaxWidthPx', label: 'Conversation width', min: 420, max: 720, step: 4, unit: 'px', integer: true },
        { kind: 'number', key: 'desktopColumnGapPx', label: 'Desktop column gap', min: 32, max: 176, step: 4, unit: 'px', integer: true },
        { kind: 'number', key: 'opticalOffsetYVh', label: 'Optical Y offset', min: -8, max: 8, step: 0.5, unit: 'svh' },
        { kind: 'number', key: 'messageMeasureCh', label: 'Message measure', min: 32, max: 64, step: 1, unit: 'ch', integer: true },
        {
          kind: 'number',
          key: 'conversationViewportHeightPx',
          label: 'Conversation minimum height',
          description: 'A floor, not a fixed size — the conversation now stretches to fill the available space above the composer; this only guards a minimum on short viewports.',
          min: 220,
          max: 560,
          step: 8,
          integer: true,
          unit: 'px',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Typography',
      fields: [
        { kind: 'number', key: 'mutedTextOpacity', label: 'Muted opacity', min: 0.35, max: 0.85, step: 0.01 },
        { kind: 'number', key: 'recapBodyTextOpacity', label: 'Recap body opacity', min: 0.65, max: 1, step: 0.01 },
      ],
    },
    // Font size / line height, segregated per breakpoint via the same
    // device-size `kind: 'tabs'` switcher AboutTimeline.panel.ts's own
    // font-size/line-height fields already use — literal Tailwind tokens
    // (components/tailwindTypographyScale.ts), not raw px/decimal numbers.
    // Excludes the top-level site nav/wordmark, which is its own separate
    // config panel (SiteHeaderConfig) — everything here is /contact's own
    // conversation/hero-greeting text. A tabs entry is a top-level scope
    // field, not nestable inside a `kind: 'group'` (see ConfigFieldTabs's
    // own doc comment, components/Panel/config/types.ts — tabs sit ABOVE
    // groups in the hierarchy), hence its own sibling entry here rather
    // than folded into the "Typography" group above.
    {
      kind: 'tabs',
      tabs: [
        {
          id: 'mobile',
          label: 'MOBILE (< 768px)',
          fields: [
            {
              kind: 'group',
              label: 'Message text',
              fields: [
                { kind: 'select', key: 'baseTextSize', label: 'Base size', options: FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'conversationTextSize', label: 'Message size', options: FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'lineHeight', label: 'Line height', options: LEADING_OPTIONS },
              ],
            },
            {
              kind: 'group',
              label: 'Hero greeting',
              fields: [
                {
                  kind: 'select',
                  key: 'heroGreetingTextSize',
                  label: 'Greeting text size',
                  description: 'Deliberately smaller than the conversation\'s own message size — auxiliary context, not a turn.',
                  options: FONT_SIZE_OPTIONS,
                },
              ],
            },
            {
              kind: 'group',
              label: 'Confirm button text',
              fields: [
                { kind: 'select', key: 'buttonFontSize', label: 'Size', options: FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'buttonFontWeight', label: 'Weight', options: FONT_WEIGHT_OPTIONS },
              ],
            },
          ],
        },
        {
          id: 'tablet',
          label: 'TABLET (≥ 768px)',
          fields: [
            {
              kind: 'group',
              label: 'Message text',
              fields: [
                { kind: 'select', key: 'baseTextSizeWide', label: 'Base size', options: MD_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'conversationTextSizeWide', label: 'Message size', options: MD_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'lineHeightWide', label: 'Line height', options: MD_LEADING_OPTIONS },
              ],
            },
            {
              kind: 'group',
              label: 'Hero greeting',
              fields: [
                { kind: 'select', key: 'heroGreetingTextSizeWide', label: 'Greeting text size', options: MD_FONT_SIZE_OPTIONS },
              ],
            },
            {
              kind: 'group',
              label: 'Confirm button text',
              fields: [
                { kind: 'select', key: 'buttonFontSizeWide', label: 'Size', options: MD_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'buttonFontWeightWide', label: 'Weight', options: CONTACT_BUTTON_FONT_WEIGHT_WIDE_OPTIONS },
              ],
            },
          ],
        },
        {
          id: 'desktop',
          label: 'DESKTOP (≥ 1024px)',
          fields: [
            {
              kind: 'group',
              label: 'Message text',
              fields: [
                { kind: 'select', key: 'baseTextSizeLg', label: 'Base size', options: LG_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'conversationTextSizeLg', label: 'Message size', options: LG_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'lineHeightLg', label: 'Line height', options: LG_LEADING_OPTIONS },
              ],
            },
            {
              kind: 'group',
              label: 'Hero greeting',
              fields: [
                { kind: 'select', key: 'heroGreetingTextSizeLg', label: 'Greeting text size', options: LG_FONT_SIZE_OPTIONS },
              ],
            },
            {
              kind: 'group',
              label: 'Confirm button text',
              fields: [
                { kind: 'select', key: 'buttonFontSizeLg', label: 'Size', options: LG_FONT_SIZE_OPTIONS },
                { kind: 'select', key: 'buttonFontWeightLg', label: 'Weight', options: CONTACT_BUTTON_FONT_WEIGHT_LG_OPTIONS },
              ],
            },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Confirm buttons',
      fields: [
        { kind: 'color', key: 'primaryButtonBackgroundColor', label: 'Primary fill (default)' },
        { kind: 'color', key: 'primaryButtonHoverActiveBackgroundColor', label: 'Primary fill (hover/active)' },
        { kind: 'color', key: 'primaryButtonBorderColor', label: 'Primary border (default)' },
        { kind: 'color', key: 'primaryButtonHoverActiveBorderColor', label: 'Primary border (hover/active)' },
        { kind: 'number', key: 'secondaryButtonBackgroundDarkenAmount', label: 'Secondary fill darken (default)', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'secondaryButtonHoverActiveBackgroundDarkenAmount', label: 'Secondary fill darken (hover/active)', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'secondaryButtonBorderDarkenAmount', label: 'Secondary border darken (default)', min: 0, max: 1, step: 0.01 },
        { kind: 'number', key: 'secondaryButtonHoverActiveBorderDarkenAmount', label: 'Secondary border darken (hover/active)', min: 0, max: 1, step: 0.01 },
        {
          kind: 'boolean',
          key: 'confirmActionsJoinedStripEnabled',
          label: 'Joined strip (mobile)',
          description: 'Off by default. On mobile only (< 768px), merges the two confirm actions into one continuous strip with a shared 1px seam instead of two independent pills — the outer corners keep their existing radius unchanged, only the inner edge squares off. Desktop is always unaffected. Both actions also drop lift/tilt/scale motion while this is on — two halves of one joined strip moving independently would look like separate objects — the accept action keeps guiding attention via color/arrow cues alone.',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer pill',
      fields: [
        { kind: 'color', key: 'composerPillBackgroundColor', label: 'Fill (default)' },
        { kind: 'color', key: 'composerPillHoverActiveBackgroundColor', label: 'Fill (hover/active)' },
        { kind: 'color', key: 'composerPillBorderColor', label: 'Border (default)' },
        { kind: 'color', key: 'composerPillHoverActiveBorderColor', label: 'Border (hover/active)' },
        { kind: 'color', key: 'composerButtonTextColor', label: 'Send button text (default)' },
        { kind: 'color', key: 'composerButtonHoverActiveTextColor', label: 'Send button text (hover/active)' },
        { kind: 'color', key: 'emptyValueActionTextColor', label: 'Empty-value link text (default)' },
        { kind: 'color', key: 'emptyValueActionHoverActiveTextColor', label: 'Empty-value link text (hover/active)' },
      ],
    },
    {
      kind: 'group',
      label: 'Rhythm and controls',
      fields: [
        { kind: 'number', key: 'messageGapPx', label: 'Message gap (between exchanges)', min: 10, max: 36, step: 1, unit: 'px', integer: true },
        {
          kind: 'select',
          key: 'messageExchangeGapClass',
          label: 'Exchange gap (question → its answer)',
          description: 'The tighter gap grouping an agent question with the visitor\'s own answer to it (and the recap\'s own intro/body/question sub-lines) into one visually chunked exchange — Gestalt proximity + cognitive-load chunking, distinct from the looser Message gap above used everywhere else.',
          options: MARGIN_TOP_OPTIONS,
        },
        { kind: 'number', key: 'controlGapPx', label: 'Control gap', min: 6, max: 28, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'actionGapPx', label: 'Action gap', min: 4, max: 24, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'chipHeightPx', label: 'Chip height', min: 40, max: 56, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'chipPaddingXPx', label: 'Chip padding', min: 12, max: 30, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'activeChipOpacity', label: 'Active chip opacity', min: 0.04, max: 0.28, step: 0.01 },
        { kind: 'boolean', key: 'showProgress', label: 'Show progress' },
      ],
    },
    {
      kind: 'group',
      label: 'Response feedback',
      fields: [
        { kind: 'boolean', key: 'loadingEffectEnabled', label: 'Loading feedback' },
        {
          kind: 'enum',
          key: 'loadingLabelMode',
          label: 'Loading label',
          options: [
            { label: 'Thinking', value: 'thinking' },
            { label: 'Submitted message', value: 'submitted-message' },
          ],
          visibleWhen: config => config.loadingEffectEnabled,
        },
        {
          kind: 'enum',
          key: 'loadingEffectStyle',
          label: 'Loading effect',
          options: [
            { label: 'Shimmer', value: 'shimmer' },
            { label: 'Pulse', value: 'pulse' },
            { label: 'Static', value: 'static' },
          ],
          visibleWhen: config => config.loadingEffectEnabled,
        },
        { kind: 'number', key: 'loadingShimmerDurationMs', label: 'Effect duration', min: 700, max: 3200, step: 50, unit: 'ms', integer: true, visibleWhen: config => config.loadingEffectEnabled && config.loadingEffectStyle !== 'static' },
        { kind: 'number', key: 'loadingMinimumVisibleMs', label: 'Minimum feedback', min: 0, max: 1200, step: 20, unit: 'ms', integer: true, visibleWhen: config => config.loadingEffectEnabled },
        { kind: 'number', key: 'messageEntryDurationMs', label: 'Message entrance', min: 0, max: 700, step: 20, unit: 'ms', integer: true },
      ],
    },
    {
      kind: 'group',
      label: 'Composer elevation',
      fields: [
        {
          kind: 'number',
          key: 'composerElevationPx',
          label: 'Composer elevation',
          description: 'The composer pill\'s own pinned shadow-engine elevation — always active, independent of the submit bounce below. Overrides the shared CTA button\'s own resting elevation just for this pill.',
          min: -8,
          max: 20,
          step: 0.5,
          unit: 'px',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer resize',
      fields: [
        {
          kind: 'number',
          key: 'composerMaxVisibleLines',
          label: 'Max visible lines',
          description: 'How many lines the composer pill grows to (on fresh composition and on "Edit note" alike) before it stops resizing and scrolls its own content internally instead. Growth only ever expands as far as the visitor\'s own content actually wraps.',
          min: 1,
          max: 10,
          step: 1,
          integer: true,
        },
        {
          kind: 'number',
          key: 'composerResizeDurationMs',
          label: 'Resize duration',
          description: 'How long the pill\'s own height takes to animate between line counts as the visitor types past a wrap point.',
          min: 0,
          max: 600,
          step: 20,
          unit: 'ms',
          integer: true,
        },
        {
          kind: 'enum',
          key: 'composerResizeEasing',
          label: 'Resize easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Conversation resume',
      fields: [
        {
          kind: 'boolean',
          key: 'conversationPersistenceEnabled',
          label: 'Enable resume',
          description: 'Persists the in-progress conversation to this device and offers to restore it on a later visit (through validity gates: schema version, TTL, phase coercion, structural shape, stale AI token). Off by default. See PLAN-CONTACT-CONVERSATION-PERSISTENCE.md.',
        },
        {
          kind: 'number',
          key: 'conversationPersistenceTtlMs',
          label: 'Resume TTL',
          description: 'How long a paused conversation stays resumable before a later visit discards it outright.',
          min: 0,
          max: 30 * 24 * 60 * 60 * 1000,
          step: 60 * 60 * 1000,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
        {
          kind: 'number',
          key: 'conversationResumeNoticeAutoDismissMs',
          label: 'Notice idle auto-dismiss',
          description: 'Optional fallback: how long the resume notice lingers with no visitor action before it fades on its own. 0 = stays until the visitor acts on the restored conversation (or clicks "Start fresh").',
          min: 0,
          max: 60000,
          step: 500,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
        {
          kind: 'number',
          key: 'resumeNoticeDismissDurationMs',
          label: 'Dismiss transition duration',
          description: 'How long the resume notice takes to fade out once the visitor acts on the restored conversation.',
          min: 0,
          max: 800,
          step: 20,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
        {
          kind: 'enum',
          key: 'resumeNoticeDismissEasing',
          label: 'Dismiss transition easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
          ],
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
        { kind: 'select', key: 'resumeNoticeFontSize', label: 'Text size', options: FONT_SIZE_OPTIONS, visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'number', key: 'resumeNoticeTextOpacity', label: 'Text opacity', min: 0, max: 1, step: 0.01, visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'number', key: 'resumeNoticeLinkOpacity', label: 'Link opacity', min: 0, max: 1, step: 0.01, visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'select', key: 'resumeNoticeLinkFontWeight', label: 'Link weight', options: FONT_WEIGHT_OPTIONS, visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'color', key: 'resumeNoticeLinkColor', label: 'Link text (default)', visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'color', key: 'resumeNoticeLinkHoverActiveColor', label: 'Link text (hover/active)', visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'select', key: 'resumeNoticePaddingX', label: 'Container padding X', options: PADDING_X_OPTIONS, visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'select', key: 'resumeNoticePaddingY', label: 'Container padding Y', options: PADDING_Y_OPTIONS, visibleWhen: config => config.conversationPersistenceEnabled },
        {
          kind: 'enum',
          key: 'resumeNoticeFillMode',
          label: 'Fill',
          options: [
            { label: 'SOLID', value: 'solid' },
            { label: 'TRANSPARENT', value: 'transparent' },
          ],
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
        { kind: 'color', key: 'resumeNoticeBackgroundColor', label: 'Fill color', visibleWhen: config => config.conversationPersistenceEnabled && config.resumeNoticeFillMode === 'solid' },
        { kind: 'number', key: 'resumeNoticeBorderWidthPx', label: 'Border thickness', description: '0 = no border.', min: 0, max: 8, step: 0.5, unit: 'px', visibleWhen: config => config.conversationPersistenceEnabled },
        { kind: 'color', key: 'resumeNoticeBorderColor', label: 'Border color', visibleWhen: config => config.conversationPersistenceEnabled && config.resumeNoticeBorderWidthPx > 0 },
        {
          kind: 'number',
          key: 'resumeNoticeElevationPx',
          label: 'Elevation',
          description: 'Drives the same shared shadow engine every other elevated surface on this page uses (useCardLiftPhysics) — not a hand-rolled shadow.',
          min: -8,
          max: 20,
          step: 0.5,
          unit: 'px',
          visibleWhen: config => config.conversationPersistenceEnabled && config.resumeNoticeShadowEnabled,
        },
        {
          kind: 'boolean',
          key: 'resumeNoticeShadowEnabled',
          label: 'Shadow enabled',
          description: 'Off: truly zero shadow, not just settled to its smallest one — elevation alone can\'t guarantee this (useCardLiftPhysics\'s own shadowEnabled doc comment).',
          visibleWhen: config => config.conversationPersistenceEnabled,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer placeholder',
      fields: [
        {
          kind: 'number',
          key: 'composerPlaceholderMinContrast',
          label: 'Placeholder minimum contrast',
          description: 'Computed the same way message text is (against the page surface color), just at a lower target than actual typed text — a dedicated contrast knob rather than an opacity dim, so the placeholder reads reliably lighter regardless of surface color.',
          min: 1,
          max: 21,
          step: 0.1,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer feedback',
      fields: [
        {
          kind: 'boolean',
          key: 'submitBounceEnabled',
          label: 'Bounce on submit',
          description: 'Off by default. Dips the composer pill and springs it back on every submit — spring stiffness/damping/duration/easing come from the shared CTA button\'s own Pond-surface bounce / State easing fields, not a separate set here.',
        },
        {
          kind: 'number',
          key: 'submitBounceElevationPx',
          label: 'Bounce elevation',
          description: 'Absolute elevation the pill dips to mid-bounce before springing back to Composer elevation above.',
          min: -8,
          max: 20,
          step: 0.5,
          unit: 'px',
          visibleWhen: config => config.submitBounceEnabled,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Retry',
      fields: [
        {
          kind: 'number',
          key: 'autoRetryDelayMs',
          label: 'Auto-retry delay',
          description: 'Wait before an automatic retry after a gap-check/recap/delivery failure. Shared across all three — only one retry sequence is ever in flight at a time.',
          min: 5000,
          max: 60000,
          step: 1000,
          integer: true,
          unit: 'ms',
        },
        {
          kind: 'number',
          key: 'autoRetryMaxCount',
          label: 'Auto-retry ceiling',
          description: 'How many automatic retries a failure gets before the flow gives up — gap-check/recap fall back to the raw-passthrough degraded message; delivery falls back to a final message pointing at the email fallback.',
          min: 0,
          max: 5,
          step: 1,
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Message appearance',
      fields: [
        {
          kind: 'enum',
          key: 'messageTextAlign',
          label: 'Message text align',
          description: 'Aligns each turn\'s own paragraph text only — every turn\'s outer block is deliberately always horizontally centered in the column regardless of this setting (the site\'s calm, editorial voice, not a per-speaker chat layout).',
          options: [
            { label: 'LEFT', value: 'left' },
            { label: 'CENTER', value: 'center' },
          ],
        },
        {
          kind: 'enum',
          key: 'messageTextColorMode',
          label: 'Message text source',
          description: 'Auto derives from the page surface color, the same way CtaButton\'s own text does; Custom uses Primary text below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'messageAutoTextMinContrast',
          label: 'Message text minimum contrast',
          description: 'Minimum contrast ratio the auto-picked message text must clear against the page surface (WCAG AA body-text floor).',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.messageTextColorMode === 'auto',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Message roles',
      fields: [
        {
          kind: 'number',
          key: 'visitorAnswerFillOpacityPercent',
          label: 'Visitor fill strength',
          description: 'How strongly the visitor-answer pill\'s fill mixes in the page\'s own border/accent color (--contact-border) — replaces a flat, barely-visible black wash with a real, colored, role-distinguishing fill.',
          min: 0,
          max: 60,
          step: 1,
          unit: '%',
        },
        { kind: 'select', key: 'visitorAnswerFontWeight', label: 'Visitor answer weight', options: FONT_WEIGHT_OPTIONS },
        {
          kind: 'number',
          key: 'visitorChoiceOpacity',
          label: 'Choice turn opacity',
          description: 'A recorded decision (e.g. "Staying anonymous") renders italic and at this opacity, independent of — and multiplied with — the position-based fade, so it always reads as distinct from an answer the visitor actually typed.',
          min: 0.2,
          max: 1,
          step: 0.02,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Reply-route error reveal',
      fields: [
        {
          kind: 'number',
          key: 'replyRouteErrorRevealStepDelayMs',
          label: 'Per-character stagger',
          description: 'How the invalid-email error message reveals letter by letter — replayed on every repeated wrong submission (never a duplicated turn, see this scope\'s own history-accuracy work) to catch the visitor\'s attention again.',
          min: 4,
          max: 60,
          step: 1,
          unit: 'ms',
        },
        {
          kind: 'number',
          key: 'replyRouteErrorRevealUnitDurationMs',
          label: 'Per-character duration',
          min: 60,
          max: 400,
          step: 10,
          unit: 'ms',
        },
        {
          kind: 'enum',
          key: 'replyRouteErrorRevealEasing',
          label: 'Per-character easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Mobile edit history fade',
      fields: [
        {
          kind: 'number',
          key: 'mobileHistoryFadeOnEditDurationMs',
          label: 'Fade duration',
          description: 'Mobile only (below Tailwind\'s md breakpoint): the turn history fades out while an in-place edit ("Edit note"/"Edit reply details") is active, then fades back in once it\'s submitted — the same duration both directions, deliberately slow/expensive rather than a snap.',
          min: 200,
          max: 1400,
          step: 20,
          unit: 'ms',
        },
        {
          kind: 'enum',
          key: 'mobileHistoryFadeOnEditEasing',
          label: 'Fade-out easing',
          description: 'The fade back IN always uses the mathematically reversed curve of this one (reverseCubicBezierEasing) — not a separate, independently-tunable field, so the two directions can never drift apart.',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Below-pill actions',
      fields: [
        {
          kind: 'boolean',
          key: 'useOriginalWordsActionEnabled',
          label: 'Use original words link',
          description: 'Off by default. When on, adds a link letting a visitor bypass the AI-organized recap and send their own raw wording verbatim, at the reply-route/name/confirm steps.',
        },
        {
          kind: 'enum',
          key: 'mandatoryActionsFontSize',
          label: 'Font size',
          description: 'The below-pill row\'s own font size — the email fallback link plus whatever step-specific link sits beside it.',
          options: [
            { label: 'XS', value: 'text-xs' },
            { label: 'SM', value: 'text-sm' },
            { label: 'BASE', value: 'text-base' },
            { label: 'LG', value: 'text-lg' },
          ],
        },
        {
          kind: 'select',
          key: 'mandatoryActionsTopGap',
          label: 'Top gap',
          description: 'The dedicated space between the dock\'s main content and this row, as a real flex gap (not padding) — independent of the message gap used within the dock above it. 0 means flush against the pill.',
          options: [
            { label: '0', value: 'gap-0' },
            { label: '1', value: 'gap-1' },
            { label: '2', value: 'gap-2' },
            { label: '3', value: 'gap-3' },
            { label: '4', value: 'gap-4' },
            { label: '5', value: 'gap-5' },
            { label: '6', value: 'gap-6' },
            { label: '8', value: 'gap-8' },
          ],
        },
        {
          kind: 'select',
          key: 'mandatoryActionsPaddingRight',
          label: 'Padding right',
          options: [
            { label: '0', value: 'pr-0' },
            { label: '1', value: 'pr-1' },
            { label: '2', value: 'pr-2' },
            { label: '3', value: 'pr-3' },
            { label: '4', value: 'pr-4' },
            { label: '5', value: 'pr-5' },
            { label: '6', value: 'pr-6' },
            { label: '8', value: 'pr-8' },
          ],
        },
        {
          kind: 'select',
          key: 'mandatoryActionsPaddingBottom',
          label: 'Padding bottom',
          options: [
            { label: '0', value: 'pb-0' },
            { label: '1', value: 'pb-1' },
            { label: '2', value: 'pb-2' },
            { label: '3', value: 'pb-3' },
            { label: '4', value: 'pb-4' },
            { label: '5', value: 'pb-5' },
            { label: '6', value: 'pb-6' },
            { label: '8', value: 'pb-8' },
          ],
        },
        {
          kind: 'select',
          key: 'mandatoryActionsPaddingLeft',
          label: 'Padding left',
          options: [
            { label: '0', value: 'pl-0' },
            { label: '1', value: 'pl-1' },
            { label: '2', value: 'pl-2' },
            { label: '3', value: 'pl-3' },
            { label: '4', value: 'pl-4' },
            { label: '6', value: 'pl-6' },
            { label: '8', value: 'pl-8' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Message fade',
      fields: [
        {
          kind: 'number',
          key: 'messageVisibleCount',
          label: 'Visible messages',
          description: 'How many of the most recent turns stay in the DOM — older turns are dropped, not just faded. Also the fade window\'s own length.',
          min: 2,
          max: 20,
          step: 1,
          integer: true,
        },
        {
          kind: 'number',
          key: 'messageFadeFloorOpacity',
          label: 'Fade floor opacity',
          description: 'Opacity the oldest visible message (the nth from the top, once the window is full) fades down to. The newest message always stays fully opaque.',
          min: 0,
          max: 1,
          step: 0.01,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Palette',
      fields: [
        {
          kind: 'color',
          key: 'primaryTextColor',
          label: 'Primary text',
          visibleWhen: config => config.messageTextColorMode === 'custom',
        },
        {
          kind: 'enum',
          key: 'mutedTextColorMode',
          label: 'Muted text source',
          description: 'Auto derives from the page surface color, same mechanism as Message text source above. Custom uses Muted text below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'mutedAutoTextMinContrast',
          label: 'Muted text minimum contrast',
          description: 'Minimum contrast ratio the auto-picked muted text must clear against the page surface — lower than the primary text floor, since this tier is meant to visually recede.',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.mutedTextColorMode === 'auto',
        },
        {
          kind: 'color',
          key: 'mutedTextColor',
          label: 'Muted text',
          visibleWhen: config => config.mutedTextColorMode === 'custom',
        },
        {
          kind: 'enum',
          key: 'borderColorMode',
          label: 'Control border source',
          description: 'Auto derives from the page surface color. Custom uses Control border below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'borderAutoTextMinContrast',
          label: 'Control border minimum contrast',
          description: 'Minimum contrast ratio the auto-picked border must clear against the page surface — a low floor, since a border only needs to be visible, not legible as text.',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.borderColorMode === 'auto',
        },
        {
          kind: 'color',
          key: 'borderColor',
          label: 'Control border',
          visibleWhen: config => config.borderColorMode === 'custom',
        },
        { kind: 'color', key: 'loadingBaseColor', label: 'Loading base' },
        { kind: 'color', key: 'loadingHighlightColor', label: 'Loading highlight' },
      ],
    },
    {
      kind: 'group',
      label: 'Hero entrance',
      fields: [
        { kind: 'number', key: 'heroContainerFadeInDurationMs', label: 'Container fade duration', min: 120, max: 900, step: 20, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroContainerFadeInEasing',
          label: 'Container fade easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'number',
          key: 'heroPlaceholderRevealInitialDelayMs',
          label: 'Placeholder reveal delay',
          description: 'Gap after the container fade finishes before the placeholder starts revealing.',
          min: 0,
          max: 600,
          step: 10,
          unit: 'ms',
          integer: true,
        },
        { kind: 'number', key: 'heroPlaceholderRevealStepDelayMs', label: 'Placeholder reveal step', description: 'Extra delay per character.', min: 6, max: 40, step: 1, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroPlaceholderRevealUnitDurationMs', label: 'Placeholder reveal duration', description: 'Duration of each character\'s own fade.', min: 80, max: 400, step: 10, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroPlaceholderRevealEasing',
          label: 'Placeholder reveal easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'enum',
          key: 'heroGreetingRevealUnit',
          label: 'Greeting reveal unit',
          description: 'Word (default) keeps a two-paragraph greeting legible while it reveals; character is better reserved for short, non-prose text.',
          options: [
            { label: 'WORD', value: 'word' },
            { label: 'CHAR', value: 'char' },
          ],
        },
        {
          kind: 'number',
          key: 'heroGreetingRevealInitialDelayMs',
          label: 'Greeting reveal delay',
          description: 'Gap after the placeholder finishes revealing before the greeting starts.',
          min: 0,
          max: 600,
          step: 10,
          unit: 'ms',
          integer: true,
        },
        { kind: 'number', key: 'heroGreetingRevealStepDelayMs', label: 'Greeting reveal step', description: 'Extra delay per word (or character).', min: 10, max: 60, step: 2, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroGreetingRevealUnitDurationMs', label: 'Greeting reveal duration', description: 'Duration of each word\'s (or character\'s) own fade.', min: 120, max: 500, step: 10, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroGreetingRevealEasing',
          label: 'Greeting reveal easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        { kind: 'number', key: 'heroGreetingGapPx', label: 'Greeting gap', description: 'Space between the greeting and the composer below it.', min: 8, max: 64, step: 2, unit: 'px', integer: true },
        {
          kind: 'number',
          key: 'heroGreetingMeasureCh',
          label: 'Greeting measure',
          description: 'Deliberately narrower than the conversation\'s own message measure, for the same reason.',
          min: 28,
          max: 56,
          step: 1,
          unit: 'ch',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer dock',
      fields: [
        {
          kind: 'number',
          key: 'composerDockTransitionDurationMs',
          label: 'Dock transition duration',
          description: 'How long the spacer below the dock takes to collapse, letting the turns-feed above claim the freed space and settle the dock at the bottom.',
          min: 300,
          max: 1400,
          step: 20,
          unit: 'ms',
          integer: true,
        },
        {
          kind: 'enum',
          key: 'composerDockTransitionEasing',
          label: 'Dock transition easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'number',
          key: 'composerDockOverlapMs',
          label: 'Bounce/dock overlap',
          description: 'Delay between the first-submit pond bounce and the dock settling starting. 0 means perfectly simultaneous.',
          min: 0,
          max: 400,
          step: 10,
          unit: 'ms',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Hero exit',
      fields: [
        { kind: 'number', key: 'heroGreetingExitDelayMs', label: 'Greeting exit delay', min: 0, max: 400, step: 10, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroGreetingExitDurationMs', label: 'Greeting exit duration', min: 300, max: 1200, step: 20, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroGreetingExitEasing',
          label: 'Greeting exit easing',
          description: 'Gaussian (ease-in-out-sine) reads as "fades out slowly" — a symmetric slow start and finish, unlike the other, front-loaded tokens.',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Carried draft handoff',
      fields: [
        {
          kind: 'number',
          key: 'carriedDraftAutoSubmitDelayMs',
          label: 'Auto-submit pause',
          description: 'When a visitor arrives here with a message already carried over from abstract.tsx\'s own composer, this is how long the composer waits after the text last changed before sending it automatically — the same submit a manual Enter press already triggers. Restarts on every keystroke.',
          min: 0,
          max: 3000,
          step: 50,
          unit: 'ms',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Confirm screen',
      fields: [
        {
          kind: 'number',
          key: 'confirmForcedHoverDelayMs',
          label: 'Accept action hover delay',
          description: 'How long the confirm screen\'s accept action ("That\'s right"/"Send it") waits, idle, before nudging attention toward it. Released the instant either action gets a real hover or focus.',
          min: 500,
          max: 4000,
          step: 100,
          unit: 'ms',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Starting points',
      fields: [
        {
          kind: 'boolean',
          key: 'starterPointsEnabled',
          label: 'Enabled',
          description: 'Master switch for the whole in-pill starters module (hint, browsing carousel, idle nudge). Off: the standard flow — a bare "Start anywhere" placeholder, nothing else.',
        },
        {
          kind: 'number',
          key: 'starterAffordanceTransitionDurationMs',
          label: 'Transition duration',
          description: 'Reused for hide-on-type, idle reappearance, the send-arrow/close-X swap, and the stem crossfade while browsing.',
          min: 100,
          max: 600,
          step: 10,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.starterPointsEnabled,
        },
        {
          kind: 'enum',
          key: 'starterAffordanceTransitionEasing',
          label: 'Transition easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
          visibleWhen: config => config.starterPointsEnabled,
        },
        {
          kind: 'number',
          key: 'starterAffordanceFadeInDurationMs',
          label: 'Reveal fade-in duration',
          description: 'The hint\'s idle fade-in only (a gentler, slower onset than the shared transition). Hide-on-type still uses the transition duration above.',
          min: 100,
          max: 900,
          step: 10,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.starterPointsEnabled,
        },
        {
          kind: 'enum',
          key: 'starterAffordanceFadeInEasing',
          label: 'Reveal fade-in easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
          visibleWhen: config => config.starterPointsEnabled,
        },
        {
          kind: 'number',
          key: 'starterAffordanceIdleReappearDelayMs',
          label: 'Idle reappear delay',
          description: 'How long the empty composer must sit engaged with no keystroke or pointer movement before "Not sure where to begin?" fades in. The countdown restarts on any activity.',
          min: 1000,
          max: 15000,
          step: 250,
          unit: 'ms',
          integer: true,
          visibleWhen: config => config.starterPointsEnabled,
        },
        {
          kind: 'boolean',
          key: 'starterAffordanceReappearAfterUse',
          label: 'Reappear after use',
          visibleWhen: config => config.starterPointsEnabled,
          description: 'Off (recommended): once the visitor has opened the starters this session, the idle hint stays away rather than re-nagging. On: it can fade back in again.',
        },
      ],
    },
  ],
  copy: {
    targetFile: 'experiences/contact/ContactExperience.config.ts',
    targetSymbol: 'DEFAULT_CONTACT_EXPERIENCE_CONFIG',
    targetType: 'ContactExperienceConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});

