import { defineConfigScope } from '../../components/Panel/config';
import {
  DEFAULT_CONTACT_EXPERIENCE_CONFIG,
  type ContactExperienceConfig,
} from './ContactExperience.config';

export const CONTACT_EXPERIENCE_SCOPE_ID = 'ContactExperience/layout-and-feedback' as const;

export const CONTACT_EXPERIENCE_PANEL = defineConfigScope<ContactExperienceConfig>({
  id: CONTACT_EXPERIENCE_SCOPE_ID,
  component: 'ContactExperience',
  scope: 'layout-and-feedback',
  title: 'Contact experience',
  createdAt: '2026-07-15',
  summary: 'Composition · typography · rhythm · response feedback',
  defaultOpen: true,
  defaultValue: DEFAULT_CONTACT_EXPERIENCE_CONFIG,
  fields: [
    {
      kind: 'group',
      label: 'Composition',
      fields: [
        { kind: 'number', key: 'conversationMaxWidthPx', label: 'Conversation width', min: 420, max: 720, step: 4, unit: 'px', integer: true },
        { kind: 'number', key: 'desktopColumnGapPx', label: 'Desktop column gap', min: 32, max: 176, step: 4, unit: 'px', integer: true },
        { kind: 'number', key: 'opticalOffsetYVh', label: 'Optical Y offset', min: -8, max: 8, step: 0.5, unit: 'svh' },
        { kind: 'number', key: 'messageMeasureCh', label: 'Message measure', min: 32, max: 64, step: 1, unit: 'ch', integer: true },
        {
          kind: 'number',
          key: 'conversationViewportHeightPx',
          label: 'Conversation minimum height',
          description: 'A floor, not a fixed size — the conversation now stretches to fill the available space above the composer; this only guards a minimum on short viewports.',
          min: 220,
          max: 560,
          step: 8,
          integer: true,
          unit: 'px',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Typography',
      fields: [
        { kind: 'number', key: 'baseTextSizePx', label: 'Base size', min: 14, max: 20, step: 0.5, unit: 'px' },
        { kind: 'number', key: 'conversationTextSizePx', label: 'Message size', min: 16, max: 24, step: 0.5, unit: 'px' },
        { kind: 'number', key: 'lineHeight', label: 'Line height', min: 1.25, max: 1.75, step: 0.01, unit: 'x' },
        { kind: 'number', key: 'mutedTextOpacity', label: 'Muted opacity', min: 0.35, max: 0.85, step: 0.01 },
        { kind: 'number', key: 'recapBodyTextOpacity', label: 'Recap body opacity', min: 0.65, max: 1, step: 0.01 },
      ],
    },
    {
      kind: 'group',
      label: 'Rhythm and controls',
      fields: [
        { kind: 'number', key: 'messageGapPx', label: 'Message gap', min: 10, max: 36, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'controlGapPx', label: 'Control gap', min: 6, max: 28, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'actionGapPx', label: 'Action gap', min: 4, max: 24, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'chipHeightPx', label: 'Chip height', min: 40, max: 56, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'chipPaddingXPx', label: 'Chip padding', min: 12, max: 30, step: 1, unit: 'px', integer: true },
        { kind: 'number', key: 'activeChipOpacity', label: 'Active chip opacity', min: 0.04, max: 0.28, step: 0.01 },
        { kind: 'boolean', key: 'showProgress', label: 'Show progress' },
      ],
    },
    {
      kind: 'group',
      label: 'Response feedback',
      fields: [
        { kind: 'boolean', key: 'loadingEffectEnabled', label: 'Loading feedback' },
        {
          kind: 'enum',
          key: 'loadingLabelMode',
          label: 'Loading label',
          options: [
            { label: 'Thinking', value: 'thinking' },
            { label: 'Submitted message', value: 'submitted-message' },
          ],
          visibleWhen: config => config.loadingEffectEnabled,
        },
        {
          kind: 'enum',
          key: 'loadingEffectStyle',
          label: 'Loading effect',
          options: [
            { label: 'Shimmer', value: 'shimmer' },
            { label: 'Pulse', value: 'pulse' },
            { label: 'Static', value: 'static' },
          ],
          visibleWhen: config => config.loadingEffectEnabled,
        },
        { kind: 'number', key: 'loadingShimmerDurationMs', label: 'Effect duration', min: 700, max: 3200, step: 50, unit: 'ms', integer: true, visibleWhen: config => config.loadingEffectEnabled && config.loadingEffectStyle !== 'static' },
        { kind: 'number', key: 'loadingMinimumVisibleMs', label: 'Minimum feedback', min: 0, max: 1200, step: 20, unit: 'ms', integer: true, visibleWhen: config => config.loadingEffectEnabled },
        { kind: 'number', key: 'messageEntryDurationMs', label: 'Message entrance', min: 0, max: 700, step: 20, unit: 'ms', integer: true },
      ],
    },
    {
      kind: 'group',
      label: 'Composer elevation',
      fields: [
        {
          kind: 'number',
          key: 'composerElevationPx',
          label: 'Composer elevation',
          description: 'The composer pill\'s own pinned shadow-engine elevation — always active, independent of the submit bounce below. Overrides the shared CTA button\'s own resting elevation just for this pill.',
          min: -8,
          max: 20,
          step: 0.5,
          unit: 'px',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer placeholder',
      fields: [
        {
          kind: 'number',
          key: 'composerPlaceholderMinContrast',
          label: 'Placeholder minimum contrast',
          description: 'Computed the same way message text is (against the page surface color), just at a lower target than actual typed text — a dedicated contrast knob rather than an opacity dim, so the placeholder reads reliably lighter regardless of surface color.',
          min: 1,
          max: 21,
          step: 0.1,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer feedback',
      fields: [
        {
          kind: 'boolean',
          key: 'submitBounceEnabled',
          label: 'Bounce on submit',
          description: 'Off by default. Dips the composer pill and springs it back on every submit — spring stiffness/damping/duration/easing come from the shared CTA button\'s own Pond-surface bounce / State easing fields, not a separate set here.',
        },
        {
          kind: 'number',
          key: 'submitBounceElevationPx',
          label: 'Bounce elevation',
          description: 'Absolute elevation the pill dips to mid-bounce before springing back to Composer elevation above.',
          min: -8,
          max: 20,
          step: 0.5,
          unit: 'px',
          visibleWhen: config => config.submitBounceEnabled,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Retry',
      fields: [
        {
          kind: 'number',
          key: 'autoRetryDelayMs',
          label: 'Auto-retry delay',
          description: 'Wait before an automatic retry after a gap-check/recap/delivery failure. Shared across all three — only one retry sequence is ever in flight at a time.',
          min: 5000,
          max: 60000,
          step: 1000,
          integer: true,
          unit: 'ms',
        },
        {
          kind: 'number',
          key: 'autoRetryMaxCount',
          label: 'Auto-retry ceiling',
          description: 'How many automatic retries a failure gets before the flow gives up — gap-check/recap fall back to the raw-passthrough degraded message; delivery falls back to a final message pointing at the email fallback.',
          min: 0,
          max: 5,
          step: 1,
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Message appearance',
      fields: [
        {
          kind: 'enum',
          key: 'messageTextAlign',
          label: 'Message text align',
          description: 'Aligns each turn\'s own paragraph text only — every turn\'s outer block is deliberately always horizontally centered in the column regardless of this setting (the site\'s calm, editorial voice, not a per-speaker chat layout).',
          options: [
            { label: 'LEFT', value: 'left' },
            { label: 'CENTER', value: 'center' },
          ],
        },
        {
          kind: 'enum',
          key: 'messageTextColorMode',
          label: 'Message text source',
          description: 'Auto derives from the page surface color, the same way CtaButton\'s own text does; Custom uses Primary text below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'messageAutoTextMinContrast',
          label: 'Message text minimum contrast',
          description: 'Minimum contrast ratio the auto-picked message text must clear against the page surface (WCAG AA body-text floor).',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.messageTextColorMode === 'auto',
        },
      ],
    },
    {
      kind: 'group',
      label: 'Message fade',
      fields: [
        {
          kind: 'number',
          key: 'messageVisibleCount',
          label: 'Visible messages',
          description: 'How many of the most recent turns stay in the DOM — older turns are dropped, not just faded. Also the fade window\'s own length.',
          min: 2,
          max: 20,
          step: 1,
          integer: true,
        },
        {
          kind: 'number',
          key: 'messageFadeFloorOpacity',
          label: 'Fade floor opacity',
          description: 'Opacity the oldest visible message (the nth from the top, once the window is full) fades down to. The newest message always stays fully opaque.',
          min: 0,
          max: 1,
          step: 0.01,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Palette',
      fields: [
        {
          kind: 'color',
          key: 'primaryTextColor',
          label: 'Primary text',
          visibleWhen: config => config.messageTextColorMode === 'custom',
        },
        {
          kind: 'enum',
          key: 'mutedTextColorMode',
          label: 'Muted text source',
          description: 'Auto derives from the page surface color, same mechanism as Message text source above. Custom uses Muted text below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'mutedAutoTextMinContrast',
          label: 'Muted text minimum contrast',
          description: 'Minimum contrast ratio the auto-picked muted text must clear against the page surface — lower than the primary text floor, since this tier is meant to visually recede.',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.mutedTextColorMode === 'auto',
        },
        {
          kind: 'color',
          key: 'mutedTextColor',
          label: 'Muted text',
          visibleWhen: config => config.mutedTextColorMode === 'custom',
        },
        {
          kind: 'enum',
          key: 'borderColorMode',
          label: 'Control border source',
          description: 'Auto derives from the page surface color. Custom uses Control border below.',
          options: [
            { label: 'AUTO', value: 'auto' },
            { label: 'CUSTOM', value: 'custom' },
          ],
        },
        {
          kind: 'number',
          key: 'borderAutoTextMinContrast',
          label: 'Control border minimum contrast',
          description: 'Minimum contrast ratio the auto-picked border must clear against the page surface — a low floor, since a border only needs to be visible, not legible as text.',
          min: 1,
          max: 21,
          step: 0.1,
          visibleWhen: config => config.borderColorMode === 'auto',
        },
        {
          kind: 'color',
          key: 'borderColor',
          label: 'Control border',
          visibleWhen: config => config.borderColorMode === 'custom',
        },
        { kind: 'color', key: 'loadingBaseColor', label: 'Loading base' },
        { kind: 'color', key: 'loadingHighlightColor', label: 'Loading highlight' },
      ],
    },
    {
      kind: 'group',
      label: 'Hero entrance',
      fields: [
        { kind: 'number', key: 'heroContainerFadeInDurationMs', label: 'Container fade duration', min: 120, max: 900, step: 20, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroContainerFadeInEasing',
          label: 'Container fade easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'number',
          key: 'heroPlaceholderRevealInitialDelayMs',
          label: 'Placeholder reveal delay',
          description: 'Gap after the container fade finishes before the placeholder starts revealing.',
          min: 0,
          max: 600,
          step: 10,
          unit: 'ms',
          integer: true,
        },
        { kind: 'number', key: 'heroPlaceholderRevealStepDelayMs', label: 'Placeholder reveal step', description: 'Extra delay per character.', min: 6, max: 40, step: 1, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroPlaceholderRevealUnitDurationMs', label: 'Placeholder reveal duration', description: 'Duration of each character\'s own fade.', min: 80, max: 400, step: 10, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroPlaceholderRevealEasing',
          label: 'Placeholder reveal easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'enum',
          key: 'heroGreetingRevealUnit',
          label: 'Greeting reveal unit',
          description: 'Word (default) keeps a two-paragraph greeting legible while it reveals; character is better reserved for short, non-prose text.',
          options: [
            { label: 'WORD', value: 'word' },
            { label: 'CHAR', value: 'char' },
          ],
        },
        {
          kind: 'number',
          key: 'heroGreetingRevealInitialDelayMs',
          label: 'Greeting reveal delay',
          description: 'Gap after the placeholder finishes revealing before the greeting starts.',
          min: 0,
          max: 600,
          step: 10,
          unit: 'ms',
          integer: true,
        },
        { kind: 'number', key: 'heroGreetingRevealStepDelayMs', label: 'Greeting reveal step', description: 'Extra delay per word (or character).', min: 10, max: 60, step: 2, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroGreetingRevealUnitDurationMs', label: 'Greeting reveal duration', description: 'Duration of each word\'s (or character\'s) own fade.', min: 120, max: 500, step: 10, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroGreetingRevealEasing',
          label: 'Greeting reveal easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        { kind: 'number', key: 'heroGreetingGapPx', label: 'Greeting gap', description: 'Space between the greeting and the composer below it.', min: 8, max: 64, step: 2, unit: 'px', integer: true },
        {
          kind: 'number',
          key: 'heroGreetingTextSizePx',
          label: 'Greeting text size',
          description: 'Deliberately smaller than the conversation\'s own message size — auxiliary context, not a turn.',
          min: 12,
          max: 20,
          step: 0.5,
          unit: 'px',
        },
        {
          kind: 'number',
          key: 'heroGreetingMeasureCh',
          label: 'Greeting measure',
          description: 'Deliberately narrower than the conversation\'s own message measure, for the same reason.',
          min: 28,
          max: 56,
          step: 1,
          unit: 'ch',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Composer dock',
      fields: [
        {
          kind: 'number',
          key: 'composerDockTransitionDurationMs',
          label: 'Dock transition duration',
          description: 'How long the spacer below the dock takes to collapse, letting the turns-feed above claim the freed space and settle the dock at the bottom.',
          min: 300,
          max: 1400,
          step: 20,
          unit: 'ms',
          integer: true,
        },
        {
          kind: 'enum',
          key: 'composerDockTransitionEasing',
          label: 'Dock transition easing',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'EXPRESSIVE', value: 'expressive' },
            { label: 'VISCOUS', value: 'viscous' },
            { label: 'GENTLE', value: 'gentle' },
          ],
        },
        {
          kind: 'number',
          key: 'composerDockOverlapMs',
          label: 'Bounce/dock overlap',
          description: 'Delay between the first-submit pond bounce and the dock settling starting. 0 means perfectly simultaneous.',
          min: 0,
          max: 400,
          step: 10,
          unit: 'ms',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Hero exit',
      fields: [
        { kind: 'number', key: 'heroGreetingExitDelayMs', label: 'Greeting exit delay', min: 0, max: 400, step: 10, unit: 'ms', integer: true },
        { kind: 'number', key: 'heroGreetingExitDurationMs', label: 'Greeting exit duration', min: 300, max: 1200, step: 20, unit: 'ms', integer: true },
        {
          kind: 'enum',
          key: 'heroGreetingExitEasing',
          label: 'Greeting exit easing',
          description: 'Gaussian (ease-in-out-sine) reads as "fades out slowly" — a symmetric slow start and finish, unlike the other, front-loaded tokens.',
          options: [
            { label: 'LINEAR', value: 'linear' },
            { label: 'STANDARD', value: 'standard' },
            { label: 'GENTLE', value: 'gentle' },
            { label: 'GAUSSIAN', value: 'gaussian' },
          ],
        },
      ],
    },
    {
      kind: 'group',
      label: 'Carried draft handoff',
      fields: [
        {
          kind: 'number',
          key: 'carriedDraftAutoSubmitDelayMs',
          label: 'Auto-submit pause',
          description: 'When a visitor arrives here with a message already carried over from abstract.tsx\'s own composer, this is how long the composer waits after the text last changed before sending it automatically — the same submit a manual Enter press already triggers. Restarts on every keystroke.',
          min: 0,
          max: 3000,
          step: 50,
          unit: 'ms',
          integer: true,
        },
      ],
    },
    {
      kind: 'group',
      label: 'Confirm screen',
      fields: [
        {
          kind: 'number',
          key: 'confirmForcedHoverDelayMs',
          label: 'Accept action hover delay',
          description: 'How long the confirm screen\'s accept action ("That\'s right"/"Send it") waits, idle, before nudging attention toward it. Released the instant either action gets a real hover or focus.',
          min: 500,
          max: 4000,
          step: 100,
          unit: 'ms',
          integer: true,
        },
      ],
    },
  ],
  copy: {
    targetFile: 'experiences/contact/ContactExperience.config.ts',
    targetSymbol: 'DEFAULT_CONTACT_EXPERIENCE_CONFIG',
    targetType: 'ContactExperienceConfig',
    updateStrategy: 'replace_scope',
    completeScope: true,
  },
});

